"""Unit tests for SubdomainService.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest_asyncio
from madewithprisme.schemas.subdomain import SubdomainCreate, SubdomainUpdate
from madewithprisme.services.subdomain import SubdomainService
from tests.factories.subdomain import SubdomainFactory


class TestSubdomainService:
    """Tests for SubdomainService CRUD operations."""

    @pytest_asyncio.fixture
    async def service(self, db):
        """Create service instance."""
        SubdomainFactory._meta.sqlalchemy_session = db
        return SubdomainService(db)

    async def test_create(self, service, db):
        """Test creating a subdomain."""
        data = SubdomainCreate(
            name="test_value_create",
        )

        result = await service.create(data=data)

        assert result is not None
        assert result.id is not None
        assert result.name is not None

    async def test_get(self, service, db):
        """Test getting a subdomain by ID."""
        instance = SubdomainFactory.create()
        await db.commit()

        result = await service.get(instance.id)

        assert result is not None
        assert result.id == instance.id

    async def test_get_not_found(self, service):
        """Test getting a non-existent subdomain."""
        result = await service.get(99999)

        assert result is None

    async def test_list(self, service, db):
        """Test listing subdomains."""
        # Create test data
        for _ in range(5):
            SubdomainFactory.create()
        await db.commit()

        results = await service.list(skip=0, limit=10)

        assert len(results) >= 5

    async def test_update(self, service, db):
        """Test updating a subdomain."""
        instance = SubdomainFactory.create()
        await db.commit()

        data = SubdomainUpdate(
            owner_id=1,
        )

        result = await service.update(id=instance.id, data=data)

        assert result is not None

    async def test_update_not_found(self, service):
        """Test updating a non-existent subdomain."""
        data = SubdomainUpdate()

        result = await service.update(id=99999, data=data)

        assert result is None

    async def test_delete(self, service, db):
        """Test deleting a subdomain."""
        instance = SubdomainFactory.create()
        await db.commit()

        result = await service.delete(id=instance.id)

        assert result is True

    async def test_delete_not_found(self, service):
        """Test deleting a non-existent subdomain."""
        result = await service.delete(id=99999)

        assert result is False
