"""Unit tests for UserService.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest_asyncio
from madewithprisme.schemas.user import UserCreate, UserUpdate
from madewithprisme.services.user import UserService
from tests.factories.user import UserFactory


class TestUserService:
    """Tests for UserService CRUD operations."""

    @pytest_asyncio.fixture
    async def service(self, db):
        """Create service instance."""
        UserFactory._meta.sqlalchemy_session = db
        return UserService(db)

    async def test_create(self, service, db):
        """Test creating a user."""
        data = UserCreate(
            email="test_create@example.com",
            email_verified=True,
            mfa_enabled=True,
            is_admin=True,
        )

        result = await service.create(data=data)

        assert result is not None
        assert result.id is not None
        assert result.email is not None
        assert result.email_verified is not None
        assert result.mfa_enabled is not None
        assert result.is_admin is not None

    async def test_get(self, service, db):
        """Test getting a user by ID."""
        instance = UserFactory.create()
        await db.commit()

        result = await service.get(instance.id)

        assert result is not None
        assert result.id == instance.id

    async def test_get_not_found(self, service):
        """Test getting a non-existent user."""
        result = await service.get(99999)

        assert result is None

    async def test_list(self, service, db):
        """Test listing users."""
        # Create test data
        for _ in range(5):
            UserFactory.create()
        await db.commit()

        results = await service.list(skip=0, limit=10)

        assert len(results) >= 5

    async def test_update(self, service, db):
        """Test updating a user."""
        instance = UserFactory.create()
        await db.commit()

        data = UserUpdate(
            password_hash="test_value_updated",
        )

        result = await service.update(id=instance.id, data=data)

        assert result is not None

    async def test_update_not_found(self, service):
        """Test updating a non-existent user."""
        data = UserUpdate()

        result = await service.update(id=99999, data=data)

        assert result is None

    async def test_delete(self, service, db):
        """Test deleting a user."""
        instance = UserFactory.create()
        await db.commit()

        result = await service.delete(id=instance.id)

        assert result is True

    async def test_delete_not_found(self, service):
        """Test deleting a non-existent user."""
        result = await service.delete(id=99999)

        assert result is False
