"""Unit tests for APIKeyService.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest_asyncio
from madewithprisme.schemas.api_key import APIKeyCreate, APIKeyUpdate
from madewithprisme.services.api_key import APIKeyService
from tests.factories.api_key import APIKeyFactory


class TestAPIKeyService:
    """Tests for APIKeyService CRUD operations."""

    @pytest_asyncio.fixture
    async def service(self, db):
        """Create service instance."""
        APIKeyFactory._meta.sqlalchemy_session = db
        return APIKeyService(db)

    async def test_create(self, service, db):
        """Test creating a api_key."""
        data = APIKeyCreate(
            user_id=1,
            key_hash="test_value",
            key_prefix="test_value",
            name="test_value",
        )

        result = await service.create(data=data)

        assert result is not None
        assert result.id is not None
        assert result.user_id is not None
        assert result.key_hash is not None
        assert result.key_prefix is not None
        assert result.name is not None

    async def test_get(self, service, db):
        """Test getting a api_key by ID."""
        instance = APIKeyFactory.create()
        await db.commit()

        result = await service.get(instance.id)

        assert result is not None
        assert result.id == instance.id

    async def test_get_not_found(self, service):
        """Test getting a non-existent api_key."""
        result = await service.get(99999)

        assert result is None

    async def test_list(self, service, db):
        """Test listing api_keys."""
        # Create test data
        for _ in range(5):
            APIKeyFactory.create()
        await db.commit()

        results = await service.list(skip=0, limit=10)

        assert len(results) >= 5

    async def test_update(self, service, db):
        """Test updating a api_key."""
        instance = APIKeyFactory.create()
        await db.commit()

        data = APIKeyUpdate(
            user_id=1,
        )

        result = await service.update(id=instance.id, data=data)

        assert result is not None

    async def test_update_not_found(self, service):
        """Test updating a non-existent api_key."""
        data = APIKeyUpdate()

        result = await service.update(id=99999, data=data)

        assert result is None

    async def test_delete(self, service, db):
        """Test deleting a api_key."""
        instance = APIKeyFactory.create()
        await db.commit()

        result = await service.delete(id=instance.id)

        assert result is True

    async def test_delete_not_found(self, service):
        """Test deleting a non-existent api_key."""
        result = await service.delete(id=99999)

        assert result is False
