"""Unit tests for AllowedEmailDomainService.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest_asyncio
from tests.factories.allowed_email_domain import AllowedEmailDomainFactory

from prisme_api.schemas.allowed_email_domain import (
    AllowedEmailDomainCreate,
    AllowedEmailDomainUpdate,
)
from prisme_api.services.allowed_email_domain import AllowedEmailDomainService


class TestAllowedEmailDomainService:
    """Tests for AllowedEmailDomainService CRUD operations."""

    @pytest_asyncio.fixture
    async def service(self, db):
        """Create service instance."""
        AllowedEmailDomainFactory._meta.sqlalchemy_session = db
        return AllowedEmailDomainService(db)

    async def test_create(self, service, db):
        """Test creating a allowed_email_domain."""
        data = AllowedEmailDomainCreate(
            domain="test_value_create",
        )

        result = await service.create(data=data)

        assert result is not None
        assert result.id is not None
        assert result.domain is not None

    async def test_get(self, service, db):
        """Test getting a allowed_email_domain by ID."""
        instance = AllowedEmailDomainFactory.create()
        await db.commit()

        result = await service.get(instance.id)

        assert result is not None
        assert result.id == instance.id

    async def test_get_not_found(self, service):
        """Test getting a non-existent allowed_email_domain."""
        result = await service.get(99999)

        assert result is None

    async def test_list(self, service, db):
        """Test listing allowed_email_domains."""
        # Create test data
        for _ in range(5):
            AllowedEmailDomainFactory.create()
        await db.commit()

        results = await service.list(skip=0, limit=10)

        assert len(results) >= 5

    async def test_update(self, service, db):
        """Test updating a allowed_email_domain."""
        instance = AllowedEmailDomainFactory.create()
        await db.commit()

        data = AllowedEmailDomainUpdate(
            is_active=True,
        )

        result = await service.update(id=instance.id, data=data)

        assert result is not None

    async def test_update_not_found(self, service):
        """Test updating a non-existent allowed_email_domain."""
        data = AllowedEmailDomainUpdate()

        result = await service.update(id=99999, data=data)

        assert result is None

    async def test_delete(self, service, db):
        """Test deleting a allowed_email_domain."""
        instance = AllowedEmailDomainFactory.create()
        await db.commit()

        result = await service.delete(id=instance.id)

        assert result is True

    async def test_delete_not_found(self, service):
        """Test deleting a non-existent allowed_email_domain."""
        result = await service.delete(id=99999)

        assert result is False
