"""Factory for AllowedEmailDomain test data.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import factory
from factory.alchemy import SQLAlchemyModelFactory

from prisme_api.models.allowed_email_domain import AllowedEmailDomain


class AllowedEmailDomainFactory(SQLAlchemyModelFactory):
    """Factory for creating AllowedEmailDomain test instances."""

    class Meta:
        model = AllowedEmailDomain
        # Disable auto-commit for async SQLAlchemy - tests call await db.commit()
        sqlalchemy_session_persistence = None

    domain = factory.Sequence(lambda n: f"domain{n}")
    is_active = factory.Faker("boolean")
    description = factory.Faker("pystr", max_chars=500)


# Convenience function
def create_allowed_email_domain(**kwargs) -> AllowedEmailDomain:
    """Create a AllowedEmailDomain instance."""
    return AllowedEmailDomainFactory.create(**kwargs)


def build_allowed_email_domain(**kwargs) -> AllowedEmailDomain:
    """Build a AllowedEmailDomain instance without saving."""
    return AllowedEmailDomainFactory.build(**kwargs)
