"""Factory for APIKey test data.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import factory
from factory.alchemy import SQLAlchemyModelFactory

from prisme_api.models.api_key import APIKey


class APIKeyFactory(SQLAlchemyModelFactory):
    """Factory for creating APIKey test instances."""

    class Meta:
        model = APIKey
        # Disable auto-commit for async SQLAlchemy - tests call await db.commit()
        sqlalchemy_session_persistence = None

    user_id = factory.Faker("random_int", min=1, max=100)
    key_hash = factory.Faker("pystr", max_chars=255)
    key_prefix = factory.Faker("pystr", max_chars=20)
    name = factory.Faker("name")
    last_used_at = factory.Faker("date_time")
    expires_at = factory.Faker("date_time")
    is_active = factory.Faker("boolean")


# Convenience function
def create_api_key(**kwargs) -> APIKey:
    """Create a APIKey instance."""
    return APIKeyFactory.create(**kwargs)


def build_api_key(**kwargs) -> APIKey:
    """Build a APIKey instance without saving."""
    return APIKeyFactory.build(**kwargs)
