"""Factory for Subdomain test data.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import factory
from factory.alchemy import SQLAlchemyModelFactory

from prisme_api.models.subdomain import Subdomain


class SubdomainFactory(SQLAlchemyModelFactory):
    """Factory for creating Subdomain test instances."""

    class Meta:
        model = Subdomain
        # Disable auto-commit for async SQLAlchemy - tests call await db.commit()
        sqlalchemy_session_persistence = None

    name = factory.Sequence(lambda n: f"name_{n}")
    owner_id = factory.Faker("random_int", min=1, max=100)
    ip_address = factory.Faker("pystr", max_chars=45)
    status = factory.Faker(
        "random_element", elements=["reserved", "active", "suspended", "released"]
    )
    dns_record_id = factory.Faker("pystr", max_chars=50)


# Convenience function
def create_subdomain(**kwargs) -> Subdomain:
    """Create a Subdomain instance."""
    return SubdomainFactory.create(**kwargs)


def build_subdomain(**kwargs) -> Subdomain:
    """Build a Subdomain instance without saving."""
    return SubdomainFactory.build(**kwargs)
