"""Factory for User test data.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import factory
from factory.alchemy import SQLAlchemyModelFactory

from prisme_api.models.user import User


class UserFactory(SQLAlchemyModelFactory):
    """Factory for creating User test instances."""

    class Meta:
        model = User
        # Disable auto-commit for async SQLAlchemy - tests call await db.commit()
        sqlalchemy_session_persistence = None

    email = factory.Sequence(lambda n: f"test{n}@example.com")
    password_hash = factory.Faker("pystr", max_chars=255)
    email_verified = factory.Faker("boolean")
    email_verification_token = factory.Faker("email")
    mfa_enabled = factory.Faker("boolean")
    mfa_secret = factory.Faker("pystr", max_chars=255)
    subdomain_limit = factory.Faker("random_int", min=1, max=1000)
    is_admin = factory.Faker("boolean")
    authentik_id = factory.Sequence(lambda n: f"authentik_id{n}")
    username = factory.Faker("name")
    roles = factory.LazyFunction(lambda: {"key": "value"})
    is_active = factory.Faker("boolean")


# Convenience function
def create_user(**kwargs) -> User:
    """Create a User instance."""
    return UserFactory.create(**kwargs)


def build_user(**kwargs) -> User:
    """Build a User instance without saving."""
    return UserFactory.build(**kwargs)
