/**
 * GraphQL queries for APIKey.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { graphql } from '../gql';

/** Get a single APIKey by ID */
export const GetAPIKeyQuery = graphql(`
  query GetAPIKey($id: Int!) {
    apikey(id: $id) {
      id
      userId
      keyHash
      keyPrefix
      name
      lastUsedAt
      expiresAt
      isActive
      createdAt
      updatedAt
      user {
        id
      }
    }
  }
`);

/** List apiKeys with pagination */
export const ListAPIKeysQuery = graphql(`
  query ListAPIKeys($pagination: OffsetPaginationInput) {
    apiKeys(pagination: $pagination) {
      edges {
        node {
          id
          userId
          keyHash
          keyPrefix
          name
          lastUsedAt
          expiresAt
          isActive
          createdAt
          updatedAt
          user {
            id
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
`);
