/**
 * GraphQL queries for Subdomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { graphql } from '../gql';

/** Get a single Subdomain by ID */
export const GetSubdomainQuery = graphql(`
  query GetSubdomain($id: Int!) {
    subdomain(id: $id) {
      id
      name
      ownerId
      ipAddress
      status
      dnsRecordId
      port
      releasedAt
      cooldownUntil
      createdAt
      updatedAt
      owner {
        id
      }
    }
  }
`);

/** List subdomains with pagination */
export const ListSubdomainsQuery = graphql(`
  query ListSubdomains($pagination: OffsetPaginationInput) {
    subdomains(pagination: $pagination) {
      edges {
        node {
          id
          name
          ownerId
          ipAddress
          status
          dnsRecordId
          port
          releasedAt
          cooldownUntil
          createdAt
          updatedAt
          owner {
            id
          }
        }
        cursor
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
`);
