/**
 * Test utilities and helpers.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import React, { type ReactElement } from 'react';
import { render, type RenderOptions } from '@testing-library/react';
import { Provider, createClient, cacheExchange, fetchExchange } from 'urql';
import { WidgetProvider } from '../prism/widgets';

// Create a mock urql client for testing
const mockClient = createClient({
  url: 'http://localhost:8000/graphql',
  exchanges: [cacheExchange, fetchExchange],
  // Disable suspense to prevent test hangs
  suspense: false,
});

// Add providers for testing
interface WrapperProps {
  children: React.ReactNode;
}

function AllTheProviders({ children }: WrapperProps): ReactElement {
  return (
    <Provider value={mockClient}>
      <WidgetProvider>
        {children}
      </WidgetProvider>
    </Provider>
  );
}

/**
 * Custom render function that wraps components with providers.
 */
function customRender(
  ui: ReactElement,
  options?: Omit<RenderOptions, 'wrapper'>
) {
  return render(ui, { wrapper: AllTheProviders, ...options });
}

// Re-export everything from Testing Library
export * from '@testing-library/react';

// Override render with custom render
export { customRender as render };

// Export mock client for advanced test cases
export { mockClient };

/**
 * Create mock data for testing.
 */
export function createMockData<T>(overrides: Partial<T> = {}): T {
  return {
    id: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  } as T;
}

/**
 * Wait for async operations.
 */
export async function waitForAsync() {
  await new Promise((resolve) => setTimeout(resolve, 0));
}
