/**
 * Hook tests for Subdomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { Provider, createClient, cacheExchange, fetchExchange } from 'urql';
import { useSubdomain, useSubdomainList, useSubdomainMutations } from '../../hooks/useSubdomain';

// Create a mock urql client
const mockClient = createClient({
  url: 'http://localhost:8000/graphql',
  exchanges: [cacheExchange, fetchExchange],
});

// Wrapper component with urql Provider
function Wrapper({ children }: { children: React.ReactNode }) {
  return <Provider value={mockClient}>{children}</Provider>;
}

describe('useSubdomain', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('returns loading state initially when id is provided', () => {
    const { result } = renderHook(() => useSubdomain(1), { wrapper: Wrapper });

    // Hook should return loading or data state
    expect(result.current).toBeDefined();
  });

  it('handles null id', () => {
    const { result } = renderHook(() => useSubdomain(null), { wrapper: Wrapper });

    // Should handle null id gracefully
    expect(result.current).toBeDefined();
  });
});

describe('useSubdomainList', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('returns initial state', () => {
    const { result } = renderHook(() => useSubdomainList(), { wrapper: Wrapper });

    expect(result.current).toBeDefined();
    expect(result.current.data).toBeDefined();
  });

  it('accepts pagination options', () => {
    const { result } = renderHook(
      () => useSubdomainList({ page: 2, pageSize: 10 }),
      { wrapper: Wrapper }
    );

    expect(result.current).toBeDefined();
  });
});

describe('useSubdomainMutations', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('provides create function', () => {
    const { result } = renderHook(() => useSubdomainMutations(), { wrapper: Wrapper });

    expect(result.current.create).toBeInstanceOf(Function);
  });

  it('provides update function', () => {
    const { result } = renderHook(() => useSubdomainMutations(), { wrapper: Wrapper });

    expect(result.current.update).toBeInstanceOf(Function);
  });

  it('provides remove function', () => {
    const { result } = renderHook(() => useSubdomainMutations(), { wrapper: Wrapper });

    expect(result.current.remove).toBeInstanceOf(Function);
  });

  it('tracks loading state', () => {
    const { result } = renderHook(() => useSubdomainMutations(), { wrapper: Wrapper });

    expect(result.current.loading).toBe(false);
  });
});
