"""Pytest configuration and shared fixtures.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import asyncio
import os
from collections.abc import AsyncGenerator, Generator

# Set test database URL before any app imports
os.environ["DATABASE_URL"] = "sqlite+aiosqlite:///:memory:"

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.pool import StaticPool

from prisme_api.models.base import Base

# Use sqlite for tests
TEST_DATABASE_URL = "sqlite+aiosqlite:///:memory:"


@pytest.fixture(scope="session")
def event_loop() -> Generator[asyncio.AbstractEventLoop]:
    """Create event loop for the test session."""
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()


@pytest_asyncio.fixture(scope="session")
async def engine():
    """Create async engine for tests."""
    engine = create_async_engine(
        TEST_DATABASE_URL,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    yield engine

    await engine.dispose()


@pytest_asyncio.fixture
async def db(engine) -> AsyncGenerator[AsyncSession]:
    """Get a test database session."""
    async_session = async_sessionmaker(
        engine,
        class_=AsyncSession,
        expire_on_commit=False,
    )

    async with async_session() as session:
        yield session
        await session.rollback()


@pytest_asyncio.fixture
async def client(db):
    """Create test client with database session and auth bypass."""
    from httpx import ASGITransport, AsyncClient

    from prisme_api.auth.dependencies import get_current_active_user
    from prisme_api.database import get_db
    from prisme_api.main import app
    from prisme_api.models.user import User

    async def override_get_db():
        yield db

    async def override_get_current_active_user():
        return User(
            id=1,
            email="test@example.com",
            is_active=True,
            email_verified=True,
            subdomain_limit=10,
            roles=["admin"],
        )

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_active_user] = override_get_current_active_user

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        yield client

    app.dependency_overrides.clear()


@pytest_asyncio.fixture
async def unauthenticated_client(db):
    """Create test client without auth override (requests will be unauthenticated)."""
    from httpx import ASGITransport, AsyncClient

    from prisme_api.database import get_db
    from prisme_api.main import app

    async def override_get_db():
        yield db

    app.dependency_overrides[get_db] = override_get_db

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        yield client

    app.dependency_overrides.clear()


@pytest_asyncio.fixture
async def authenticated_client(db):
    """Client with a real persisted user for authenticated endpoint tests."""
    import uuid

    from httpx import ASGITransport, AsyncClient

    from prisme_api.auth.dependencies import get_current_active_user
    from prisme_api.auth.utils import hash_password
    from prisme_api.database import get_db
    from prisme_api.main import app
    from prisme_api.models.user import User

    unique = uuid.uuid4().hex[:8]
    user = User(
        email=f"authuser-{unique}@example.com",
        username=f"authuser-{unique}",
        password_hash=hash_password("StrongPass1"),
        email_verified=True,
        is_active=True,
        roles=["admin"],
        failed_login_attempts=0,
    )
    db.add(user)
    await db.commit()
    await db.refresh(user)

    async def override_get_db():
        yield db

    async def override_get_current_active_user():
        await db.refresh(user)
        return user

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[get_current_active_user] = override_get_current_active_user

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        yield client

    app.dependency_overrides.clear()
