# Production Environment Configuration for prisme-saas
# Generated by Prism
#
# Usage: terraform plan -var-file=production.tfvars

# Deploy production (optionally keep staging running)
deploy_staging    = false
deploy_production = true

# Server configuration
production_server_type = "cx21"
production_volume_size = 20
production_floating_ip = true

# Location
location = "nbg1"
