# Staging Environment Configuration for prisme-saas
# Generated by Prism
#
# Usage: terraform plan -var-file=staging.tfvars

# Deploy staging only
deploy_staging    = true
deploy_production = false

# Server configuration
staging_server_type = "cx23"
staging_volume_size = 10

# Location
location = "nbg1"
