# Variables for Hetzner Infrastructure
# Generated by Prism

# =============================================================================
# Project Configuration
# =============================================================================

variable "project_name" {
  description = "Project name used for resource naming"
  type        = string
  default     = "prisme-saas"
}

variable "domain" {
  description = "Base domain for the application"
  type        = string
  default     = "madewithpris.me"
}

variable "github_repository" {
  description = "GitHub repository (owner/repo) for container images"
  type        = string
  default     = "lassethomsen/prisme-saas"
}

# =============================================================================
# Authentication
# =============================================================================

variable "hcloud_token" {
  description = "Hetzner Cloud API token"
  type        = string
  sensitive   = true
}

variable "ssh_public_key" {
  description = "SSH public key for server access"
  type        = string
}

# =============================================================================
# Location
# =============================================================================

variable "location" {
  description = "Hetzner datacenter location (nbg1, fsn1, hel1, ash, hil)"
  type        = string
  default     = "nbg1"
}

# =============================================================================
# Environment Toggles
# =============================================================================

variable "deploy_staging" {
  description = "Whether to deploy staging environment"
  type        = bool
  default     = true
}

variable "deploy_production" {
  description = "Whether to deploy production environment"
  type        = bool
  default     = false
}

# =============================================================================
# Staging Configuration
# =============================================================================

variable "staging_server_type" {
  description = "Server type for staging (cx11, cx21, cx31, cx41, cx51)"
  type        = string
  default     = "cx11"
}

variable "staging_volume_size" {
  description = "Volume size in GB for staging PostgreSQL data"
  type        = number
  default     = 10
}

# =============================================================================
# Production Configuration
# =============================================================================

variable "production_server_type" {
  description = "Server type for production (cx21, cx31, cx41, cx51)"
  type        = string
  default     = "cx21"
}

variable "production_volume_size" {
  description = "Volume size in GB for production PostgreSQL data"
  type        = number
  default     = 20
}

variable "production_floating_ip" {
  description = "Whether to attach a floating IP to production server"
  type        = bool
  default     = true
}
