# Terraform version constraints for prisme-saas
# Generated by Prism

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.45"
    }
  }

  # Uncomment to use remote state (recommended for team usage)
  # backend "s3" {
  #   bucket         = "prisme_saas-terraform-state"
  #   key            = "hetzner/terraform.tfstate"
  #   region         = "eu-central-1"
  #   encrypt        = true
  #   dynamodb_table = "prisme_saas-terraform-locks"
  # }
}
