/**
 * GraphQL fragment for AllowedEmailDomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { graphql } from '../gql';

export const AllowedEmailDomainFragment = graphql(`
  fragment AllowedEmailDomainFragment on AllowedEmailDomainType {
    id
    domain
    isActive
    description
    createdAt
    updatedAt
  }
`);

export const AllowedEmailDomainFields = `
    id
    domain
    isActive
    description
    createdAt
    updatedAt
`;
