/**
 * GraphQL fragment for APIKey.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { graphql } from '../gql';

export const APIKeyFragment = graphql(`
  fragment APIKeyFragment on APIKeyType {
    id
    userId
    keyHash
    keyPrefix
    name
    lastUsedAt
    expiresAt
    isActive
    createdAt
    updatedAt
    user {
      id
    }
  }
`);

export const APIKeyFields = `
    id
    userId
    keyHash
    keyPrefix
    name
    lastUsedAt
    expiresAt
    isActive
    createdAt
    updatedAt
    user {
      id
    }
`;
