/**
 * GraphQL fragment for Subdomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { graphql } from '../gql';

export const SubdomainFragment = graphql(`
  fragment SubdomainFragment on SubdomainType {
    id
    name
    ownerId
    ipAddress
    status
    dnsRecordId
    createdAt
    updatedAt
    owner {
      id
    }
  }
`);

export const SubdomainFields = `
    id
    name
    ownerId
    ipAddress
    status
    dnsRecordId
    createdAt
    updatedAt
    owner {
      id
    }
`;
