/**
 * GraphQL fragment for User.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { graphql } from '../gql';

export const UserFragment = graphql(`
  fragment UserFragment on UserType {
    id
    email
    passwordHash
    emailVerified
    emailVerificationToken
    mfaEnabled
    mfaSecret
    subdomainLimit
    isAdmin
    authentikId
    username
    roles
    isActive
    createdAt
    updatedAt
    deletedAt
    apiKeys {
      id
    }
    subdomains {
      id
    }
  }
`);

export const UserFields = `
    id
    email
    passwordHash
    emailVerified
    emailVerificationToken
    mfaEnabled
    mfaSecret
    subdomainLimit
    isAdmin
    authentikId
    username
    roles
    isActive
    createdAt
    updatedAt
    deletedAt
    apiKeys {
      id
    }
    subdomains {
      id
    }
`;
