"""API integration tests for User.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest
from tests.factories.user import UserFactory


class TestUserAPI:
    """API integration tests for User endpoints."""

    @pytest.mark.asyncio
    async def test_list_users(self, client, db):
        """Test GET /users"""
        # Create test data
        UserFactory._meta.sqlalchemy_session = db
        for _ in range(3):
            UserFactory.create()
        await db.commit()

        response = await client.get("/api/users")

        assert response.status_code == 200
        data = response.json()
        assert "items" in data
        assert len(data["items"]) >= 3

    @pytest.mark.asyncio
    async def test_get_user(self, client, db):
        """Test GET /users/{id}"""
        UserFactory._meta.sqlalchemy_session = db
        instance = UserFactory.create()
        await db.commit()

        response = await client.get(f"/api/users/{instance.id}")

        assert response.status_code == 200
        data = response.json()
        assert data["id"] == instance.id

    @pytest.mark.asyncio
    async def test_get_user_not_found(self, client):
        """Test GET /users/{id} with invalid ID"""
        response = await client.get("/api/users/99999")

        assert response.status_code == 404

    @pytest.mark.asyncio
    async def test_create_user(self, client):
        """Test POST /users"""
        payload = {
            "email": "test_api@example.com",
            "email_verified": True,
            "mfa_enabled": True,
            "is_admin": True,
        }

        response = await client.post("/api/users", json=payload)

        assert response.status_code == 201
        data = response.json()
        assert "id" in data

    @pytest.mark.asyncio
    async def test_update_user(self, client, db):
        """Test PATCH /users/{id}"""
        UserFactory._meta.sqlalchemy_session = db
        instance = UserFactory.create()
        await db.commit()

        payload = {
            "password_hash": "test_value_updated",
        }

        response = await client.patch(f"/api/users/{instance.id}", json=payload)

        assert response.status_code == 200

    @pytest.mark.asyncio
    async def test_delete_user(self, client, db):
        """Test DELETE /users/{id}"""
        UserFactory._meta.sqlalchemy_session = db
        instance = UserFactory.create()
        await db.commit()

        response = await client.delete(f"/api/users/{instance.id}")

        assert response.status_code == 204
