"""API integration tests for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest
from tests.factories.subdomain import SubdomainFactory


class TestSubdomainAPI:
    """API integration tests for Subdomain endpoints."""

    @pytest.mark.asyncio
    async def test_list_subdomains(self, client, db):
        """Test GET /subdomains"""
        # Create test data
        SubdomainFactory._meta.sqlalchemy_session = db
        for _ in range(3):
            SubdomainFactory.create()
        await db.commit()

        response = await client.get("/api/subdomains")

        assert response.status_code == 200
        data = response.json()
        assert "items" in data
        assert len(data["items"]) >= 3

    @pytest.mark.asyncio
    async def test_get_subdomain(self, client, db):
        """Test GET /subdomains/{id}"""
        SubdomainFactory._meta.sqlalchemy_session = db
        instance = SubdomainFactory.create()
        await db.commit()

        response = await client.get(f"/api/subdomains/{instance.id}")

        assert response.status_code == 200
        data = response.json()
        assert data["id"] == instance.id

    @pytest.mark.asyncio
    async def test_get_subdomain_not_found(self, client):
        """Test GET /subdomains/{id} with invalid ID"""
        response = await client.get("/api/subdomains/99999")

        assert response.status_code == 404

    @pytest.mark.asyncio
    async def test_create_subdomain(self, client):
        """Test POST /subdomains"""
        payload = {
            "name": "test_value_api",
        }

        response = await client.post("/api/subdomains", json=payload)

        assert response.status_code == 201
        data = response.json()
        assert "id" in data

    @pytest.mark.asyncio
    async def test_update_subdomain(self, client, db):
        """Test PATCH /subdomains/{id}"""
        SubdomainFactory._meta.sqlalchemy_session = db
        instance = SubdomainFactory.create()
        await db.commit()

        payload = {
            "owner_id": 1,
        }

        response = await client.patch(f"/api/subdomains/{instance.id}", json=payload)

        assert response.status_code == 200

    @pytest.mark.asyncio
    async def test_delete_subdomain(self, client, db):
        """Test DELETE /subdomains/{id}"""
        SubdomainFactory._meta.sqlalchemy_session = db
        instance = SubdomainFactory.create()
        await db.commit()

        response = await client.delete(f"/api/subdomains/{instance.id}")

        assert response.status_code == 204
