"""API integration tests for APIKey.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest
from tests.factories.api_key import APIKeyFactory


class TestAPIKeyAPI:
    """API integration tests for APIKey endpoints."""

    @pytest.mark.asyncio
    async def test_list_api_keys(self, client, db):
        """Test GET /api-keys"""
        # Create test data
        APIKeyFactory._meta.sqlalchemy_session = db
        for _ in range(3):
            APIKeyFactory.create()
        await db.commit()

        response = await client.get("/api/api-keys")

        assert response.status_code == 200
        data = response.json()
        assert "items" in data
        assert len(data["items"]) >= 3

    @pytest.mark.asyncio
    async def test_get_api_key(self, client, db):
        """Test GET /api-keys/{id}"""
        APIKeyFactory._meta.sqlalchemy_session = db
        instance = APIKeyFactory.create()
        await db.commit()

        response = await client.get(f"/api/api-keys/{instance.id}")

        assert response.status_code == 200
        data = response.json()
        assert data["id"] == instance.id

    @pytest.mark.asyncio
    async def test_get_api_key_not_found(self, client):
        """Test GET /api-keys/{id} with invalid ID"""
        response = await client.get("/api/api-keys/99999")

        assert response.status_code == 404

    @pytest.mark.asyncio
    async def test_create_api_key(self, client):
        """Test POST /api-keys"""
        payload = {
            "user_id": 1,
            "key_hash": "test_value",
            "key_prefix": "test_value",
            "name": "test_value",
        }

        response = await client.post("/api/api-keys", json=payload)

        assert response.status_code == 201
        data = response.json()
        assert "id" in data

    @pytest.mark.asyncio
    async def test_update_api_key(self, client, db):
        """Test PATCH /api-keys/{id}"""
        APIKeyFactory._meta.sqlalchemy_session = db
        instance = APIKeyFactory.create()
        await db.commit()

        payload = {
            "user_id": 1,
        }

        response = await client.patch(f"/api/api-keys/{instance.id}", json=payload)

        assert response.status_code == 200

    @pytest.mark.asyncio
    async def test_delete_api_key(self, client, db):
        """Test DELETE /api-keys/{id}"""
        APIKeyFactory._meta.sqlalchemy_session = db
        instance = APIKeyFactory.create()
        await db.commit()

        response = await client.delete(f"/api/api-keys/{instance.id}")

        assert response.status_code == 204
