/**
 * Protected Route Component
 *
 * AUTO-GENERATED BY PRISM - DO NOT EDIT
 * Wrapper component for routes that require authentication.
 */

import { Navigate, useLocation, Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import type { ReactNode } from 'react';

interface ProtectedRouteProps {
  /** Child components to render if authenticated */
  children: ReactNode;
  /** Required roles (user must have at least one) */
  roles?: string[];
  /** Redirect path for unauthenticated users */
  redirectTo?: string;
  /** Component to show while loading */
  loadingComponent?: ReactNode;
  /** Component to show for unauthorized access (authenticated but missing role) */
  unauthorizedComponent?: ReactNode;
}

/**
 * Wrapper component that protects routes requiring authentication.
 *
 * @example
 * ```tsx
 * // Basic protection
 * <ProtectedRoute>
 *   <Dashboard />
 * </ProtectedRoute>
 *
 * // With role requirement
 * <ProtectedRoute roles={['admin']}>
 *   <AdminPanel />
 * </ProtectedRoute>
 *
 * // With custom loading
 * <ProtectedRoute loadingComponent={<CustomSpinner />}>
 *   <Dashboard />
 * </ProtectedRoute>
 * ```
 */
export function ProtectedRoute({
  children,
  roles,
  redirectTo = '/login',
  loadingComponent,
  unauthorizedComponent,
}: ProtectedRouteProps) {
  const { isAuthenticated, isLoading, hasAnyRole } = useAuth();
  const location = useLocation();

  // Show loading state
  if (isLoading) {
    if (loadingComponent) {
      return <>{loadingComponent}</>;
    }

    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  // Redirect if not authenticated
  if (!isAuthenticated) {
    // Store intended destination for redirect after login
    sessionStorage.setItem('auth_return_to', location.pathname + location.search);

    return <Navigate to={redirectTo} state={{ from: location }} replace />;
  }

  // Check roles if specified
  if (roles && roles.length > 0 && !hasAnyRole(...roles)) {
    if (unauthorizedComponent) {
      return <>{unauthorizedComponent}</>;
    }

    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="max-w-md w-full p-6 bg-white rounded-lg shadow-md text-center">
          <h1 className="text-2xl font-bold text-red-600 mb-4">
            Access Denied
          </h1>
          <p className="text-gray-600 mb-4">
            You don't have permission to access this page.
          </p>
          <p className="text-sm text-gray-500 mb-4">
            Required roles: {roles.join(', ')}
          </p>
          <Link
            to="/"
            className="inline-block py-2 px-4 bg-nordic-600 text-white rounded-md hover:bg-nordic-700 transition-colors text-sm font-medium"
          >
            Go to homepage
          </Link>
        </div>
      </div>
    );
  }

  return <>{children}</>;
}

export default ProtectedRoute;
