"""MCP server authentication.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT

SECURITY: All MCP tools require admin API key authentication.
Set MCP_ADMIN_API_KEY environment variable.
"""

from __future__ import annotations

import os
from collections.abc import Callable
from functools import wraps
from typing import Any

# MCP Admin API key from environment
MCP_ADMIN_API_KEY = os.getenv("MCP_ADMIN_API_KEY", "")


def require_mcp_auth(func: Callable) -> Callable:
    """Decorator to require MCP admin API key authentication.

    Tools wrapped with this decorator require the _api_key parameter
    to match the MCP_ADMIN_API_KEY environment variable.

    Usage:
        @mcp.tool()
        @require_mcp_auth
        async def my_tool(_api_key: str = "") -> dict:
            ...
    """

    @wraps(func)
    async def wrapper(*args: Any, **kwargs: Any) -> dict[str, Any]:
        api_key = kwargs.pop("_api_key", "")

        if not MCP_ADMIN_API_KEY:
            return {"error": "MCP_ADMIN_API_KEY not configured on server"}

        if not api_key or api_key != MCP_ADMIN_API_KEY:
            return {"error": "Unauthorized - admin API key required"}

        return await func(*args, **kwargs)

    return wrapper


__all__ = ["MCP_ADMIN_API_KEY", "require_mcp_auth"]
