"""SQLAlchemy model for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin

if TYPE_CHECKING:
    from .user import User


class Subdomain(Base, TimestampMixin):
    """A managed madewithpris.me subdomain"""

    __tablename__ = "subdomains"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(63), unique=True, index=True)
    owner_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=True
    )
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)
    status: Mapped[str] = mapped_column(
        Enum("reserved", "active", "suspended", "released", name="subdomain_status_enum"),
        index=True,
        default="reserved",
    )
    dns_record_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    port: Mapped[int] = mapped_column(Integer, default=80)
    released_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    cooldown_until: Mapped[datetime | None] = mapped_column(DateTime, index=True, nullable=True)

    # Relationships
    owner: Mapped[User | None] = relationship("User", back_populates="subdomains")
