"""SQLAlchemy model for User.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import Boolean, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, SoftDeleteMixin, TimestampMixin

if TYPE_CHECKING:
    from .api_key import APIKey
    from .subdomain import Subdomain


class User(Base, TimestampMixin, SoftDeleteMixin):
    """User account for prisme.dev"""

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    password_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email_verified: Mapped[bool] = mapped_column(Boolean, default=False)
    email_verification_token: Mapped[str | None] = mapped_column(String(255), nullable=True)
    mfa_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    mfa_secret: Mapped[str | None] = mapped_column(String(255), nullable=True)
    subdomain_limit: Mapped[int] = mapped_column(Integer, default=5)
    is_admin: Mapped[bool] = mapped_column(Boolean, default=False)

    # Relationships
    api_keys: Mapped[list[APIKey]] = relationship("APIKey", back_populates="user")
    subdomains: Mapped[list[Subdomain]] = relationship("Subdomain", back_populates="owner")
