/**
 * Base form component for AllowedEmailDomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { type ReactElement } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { useWidgetRegistry } from '../../prism/widgets';
import type { FieldSpec } from '../../prism/widgets/types';
import type { AllowedEmailDomainCreate } from '../../types/generated';

/** Field specifications for AllowedEmailDomain form */
export const ALLOWEDEMAILDOMAIN_FIELD_SPECS: FieldSpec[] = [
  { name: 'domain', type: 'string', required: true, displayName: 'Domain', description: 'Email domain (e.g., \'example.com\')' },
  { name: 'isActive', type: 'boolean', required: false, displayName: 'Is Active', description: 'Whether this domain is currently allowed' },
  { name: 'description', type: 'string', required: false, displayName: 'Description', description: 'Optional description/notes about this domain' }
];

export interface AllowedEmailDomainFormBaseProps {
  /** Form submission handler */
  onSubmit: (data: AllowedEmailDomainCreate) => void | Promise<void>;
  /** Default values for the form */
  defaultValues?: Partial<AllowedEmailDomainCreate>;
  /** Loading state */
  loading?: boolean;
  /** Submit button text */
  submitLabel?: string;
  /** Cancel handler */
  onCancel?: () => void;
}

/**
 * Base form component for creating/editing AllowedEmailDomain.
 * Extend this in components/allowed-email-domain/AllowedEmailDomainForm.tsx
 */
export function AllowedEmailDomainFormBase({
  onSubmit,
  defaultValues,
  loading = false,
  submitLabel = 'Save',
  onCancel,
}: AllowedEmailDomainFormBaseProps): ReactElement {
  const registry = useWidgetRegistry();
  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<AllowedEmailDomainCreate>({ defaultValues });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      {ALLOWEDEMAILDOMAIN_FIELD_SPECS.map((field) => {
        const Widget = registry.resolve(
          'AllowedEmailDomain',
          field.name,
          field.type,
          field.uiWidget
        );

        return (
          <Controller
            key={field.name}
            name={field.name as keyof AllowedEmailDomainCreate}
            control={control}
            rules={{ required: field.required }}
            render={({ field: { onChange, value } }) => (
              <Widget
                name={field.name}
                value={value}
                onChange={onChange}
                label={field.displayName ?? field.name}
                description={field.description}
                placeholder={field.placeholder}
                required={field.required}
                disabled={loading}
                error={errors[field.name as keyof AllowedEmailDomainCreate]?.message}
                options={field.enumValues}
                references={field.references}
                {...field.widgetProps}
              />
            )}
          />
        );
      })}

      <div className="flex items-center justify-end gap-3 pt-4 border-t border-nordic-100">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            disabled={loading}
            className="btn-secondary"
          >
            Cancel
          </button>
        )}
        <button type="submit" disabled={loading} className="btn-primary">
          {loading ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Saving...
            </span>
          ) : submitLabel}
        </button>
      </div>
    </form>
  );
}
