/**
 * Base form component for APIKey.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { type ReactElement } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { useWidgetRegistry } from '../../prism/widgets';
import type { FieldSpec } from '../../prism/widgets/types';
import type { APIKeyCreate } from '../../types/generated';

/** Field specifications for APIKey form */
export const APIKEY_FIELD_SPECS: FieldSpec[] = [
  { name: 'userId', type: 'foreign_key', required: true, displayName: 'User Id', description: 'The user who owns this API key', references: 'User' },
  { name: 'keyPrefix', type: 'string', required: true, displayName: 'Key Prefix', description: 'API key prefix for identification (e.g., prisme_live_sk_xxx)' },
  { name: 'name', type: 'string', required: true, displayName: 'Name', description: 'Human-readable name for the API key' },
  { name: 'lastUsedAt', type: 'datetime', required: false, displayName: 'Last Used At', description: 'Last time this API key was used' },
  { name: 'expiresAt', type: 'datetime', required: false, displayName: 'Expires At', description: 'When this API key expires (null = never)' },
  { name: 'isActive', type: 'boolean', required: false, displayName: 'Is Active', description: 'Whether this API key is active' }
];

export interface APIKeyFormBaseProps {
  /** Form submission handler */
  onSubmit: (data: APIKeyCreate) => void | Promise<void>;
  /** Default values for the form */
  defaultValues?: Partial<APIKeyCreate>;
  /** Loading state */
  loading?: boolean;
  /** Submit button text */
  submitLabel?: string;
  /** Cancel handler */
  onCancel?: () => void;
}

/**
 * Base form component for creating/editing APIKey.
 * Extend this in components/api-key/APIKeyForm.tsx
 */
export function APIKeyFormBase({
  onSubmit,
  defaultValues,
  loading = false,
  submitLabel = 'Save',
  onCancel,
}: APIKeyFormBaseProps): ReactElement {
  const registry = useWidgetRegistry();
  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<APIKeyCreate>({ defaultValues });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      {APIKEY_FIELD_SPECS.map((field) => {
        const Widget = registry.resolve(
          'APIKey',
          field.name,
          field.type,
          field.uiWidget
        );

        return (
          <Controller
            key={field.name}
            name={field.name as keyof APIKeyCreate}
            control={control}
            rules={{ required: field.required }}
            render={({ field: { onChange, value } }) => (
              <Widget
                name={field.name}
                value={value}
                onChange={onChange}
                label={field.displayName ?? field.name}
                description={field.description}
                placeholder={field.placeholder}
                required={field.required}
                disabled={loading}
                error={errors[field.name as keyof APIKeyCreate]?.message}
                options={field.enumValues}
                references={field.references}
                {...field.widgetProps}
              />
            )}
          />
        );
      })}

      <div className="flex items-center justify-end gap-3 pt-4 border-t border-nordic-100">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            disabled={loading}
            className="btn-secondary"
          >
            Cancel
          </button>
        )}
        <button type="submit" disabled={loading} className="btn-primary">
          {loading ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Saving...
            </span>
          ) : submitLabel}
        </button>
      </div>
    </form>
  );
}
