/**
 * Base table component for APIKey.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { type ReactElement } from 'react';
import type { APIKey } from '../../types/generated';

/** Column definitions for APIKey table */
export const APIKEY_COLUMNS = [
  { key: 'userId', label: 'User Id', tooltip: 'The user who owns this API key' },
  { key: 'keyPrefix', label: 'Key Prefix', tooltip: 'API key prefix for identification (e.g., prisme_live_sk_xxx)' },
  { key: 'name', label: 'Name', tooltip: 'Human-readable name for the API key' },
  { key: 'lastUsedAt', label: 'Last Used At', tooltip: 'Last time this API key was used' },
  { key: 'expiresAt', label: 'Expires At', tooltip: 'When this API key expires (null = never)' },
  { key: 'isActive', label: 'Is Active', tooltip: 'Whether this API key is active' }
];

export interface APIKeyTableBaseProps {
  /** Data to display */
  data: APIKey[];
  /** Loading state */
  loading?: boolean;
  /** Row click handler */
  onRowClick?: (item: APIKey) => void;
  /** Edit action handler */
  onEdit?: (item: APIKey) => void;
  /** Delete action handler */
  onDelete?: (item: APIKey) => void;
  /** Selected row IDs */
  selectedIds?: number[];
  /** Selection change handler */
  onSelectionChange?: (ids: number[]) => void;
}

/**
 * Base table component for displaying APIKeys.
 * Extend this in components/api-key/APIKeyTable.tsx
 */
export function APIKeyTableBase({
  data,
  loading = false,
  onRowClick,
  onEdit,
  onDelete,
  selectedIds = [],
  onSelectionChange,
}: APIKeyTableBaseProps): ReactElement {
  const handleSelect = (id: number) => {
    if (!onSelectionChange) return;
    if (selectedIds.includes(id)) {
      onSelectionChange(selectedIds.filter((i) => i !== id));
    } else {
      onSelectionChange([...selectedIds, id]);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-pulse flex items-center gap-3">
          <div className="w-2 h-2 bg-nordic-400 rounded-full animate-bounce" />
          <div className="w-2 h-2 bg-nordic-400 rounded-full animate-bounce [animation-delay:0.1s]" />
          <div className="w-2 h-2 bg-nordic-400 rounded-full animate-bounce [animation-delay:0.2s]" />
        </div>
      </div>
    );
  }

  if (data.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <div className="w-12 h-12 bg-nordic-100 rounded-full flex items-center justify-center mb-3">
          <svg className="w-6 h-6 text-nordic-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
          </svg>
        </div>
        <p className="text-nordic-500">No apikeys found.</p>
      </div>
    );
  }

  return (
    <table className="table">
      <thead>
        <tr>
          {onSelectionChange && <th className="w-12" />}
          {APIKEY_COLUMNS.map((col) => (
            <th key={col.key}>
              {col.label}
            </th>
          ))}
          {(onEdit || onDelete) && <th className="w-32 text-right">Actions</th>}
        </tr>
      </thead>
      <tbody>
        {data.map((item) => (
          <tr
            key={item.id}
            onClick={() => onRowClick?.(item)}
            className={`${onRowClick ? 'cursor-pointer' : ''} ${selectedIds.includes(item.id) ? 'bg-accent-50' : ''}`}
          >
            {onSelectionChange && (
              <td>
                <input
                  type="checkbox"
                  checked={selectedIds.includes(item.id)}
                  onChange={() => handleSelect(item.id)}
                  onClick={(e) => e.stopPropagation()}
                  className="checkbox"
                />
              </td>
            )}
            {APIKEY_COLUMNS.map((col) => (
              <td key={col.key} className="text-nordic-700">
                {col.render ? col.render(item) : String(item[col.key as keyof APIKey] ?? '')}
              </td>
            ))}
            {(onEdit || onDelete) && (
              <td className="text-right">
                <div className="flex items-center justify-end gap-2">
                  {onEdit && (
                    <button
                      onClick={(e) => { e.stopPropagation(); onEdit(item); }}
                      className="btn-ghost text-xs px-2 py-1"
                    >
                      Edit
                    </button>
                  )}
                  {onDelete && (
                    <button
                      onClick={(e) => { e.stopPropagation(); onDelete(item); }}
                      className="btn-ghost text-xs px-2 py-1 text-red-600 hover:text-red-700 hover:bg-red-50"
                    >
                      Delete
                    </button>
                  )}
                </div>
              </td>
            )}
          </tr>
        ))}
      </tbody>
    </table>
  );
}
