/**
 * Generated components index.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */export { UserFormBase, USER_FIELD_SPECS } from './UserFormBase';export { UserTableBase, USER_COLUMNS } from './UserTableBase';export { UserDetailBase } from './UserDetailBase';export { APIKeyFormBase, APIKEY_FIELD_SPECS } from './APIKeyFormBase';export { APIKeyTableBase, APIKEY_COLUMNS } from './APIKeyTableBase';export { APIKeyDetailBase } from './APIKeyDetailBase';export { SubdomainFormBase, SUBDOMAIN_FIELD_SPECS } from './SubdomainFormBase';export { SubdomainTableBase, SUBDOMAIN_COLUMNS } from './SubdomainTableBase';export { SubdomainDetailBase } from './SubdomainDetailBase';export { AllowedEmailDomainFormBase, ALLOWEDEMAILDOMAIN_FIELD_SPECS } from './AllowedEmailDomainFormBase';export { AllowedEmailDomainTableBase, ALLOWEDEMAILDOMAIN_COLUMNS } from './AllowedEmailDomainTableBase';export { AllowedEmailDomainDetailBase } from './AllowedEmailDomainDetailBase';
