/**
 * Base form component for Subdomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { type ReactElement } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { useWidgetRegistry } from '../../prism/widgets';
import type { FieldSpec } from '../../prism/widgets/types';
import type { SubdomainCreate } from '../../types/generated';

/** Field specifications for Subdomain form */
export const SUBDOMAIN_FIELD_SPECS: FieldSpec[] = [
  { name: 'name', type: 'string', required: true, displayName: 'Name', description: 'Subdomain name (e.g., \'myapp\')' },
  { name: 'ownerId', type: 'foreign_key', required: false, displayName: 'Owner Id', description: 'The user who owns this subdomain', references: 'User' },
  { name: 'ipAddress', type: 'string', required: false, displayName: 'Ip Address', description: 'IPv4 address for the A record' },
  { name: 'status', type: 'enum', required: false, displayName: 'Status', description: 'Current status of the subdomain', enumValues: ['reserved', 'active', 'suspended', 'released'] },
  { name: 'dnsRecordId', type: 'string', required: false, displayName: 'Dns Record Id', description: 'Hetzner DNS record ID' },
  { name: 'port', type: 'integer', required: false, displayName: 'Port', description: 'Target port for routing (default: 80)' },
  { name: 'releasedAt', type: 'datetime', required: false, displayName: 'Released At', description: 'When the subdomain was released' },
  { name: 'cooldownUntil', type: 'datetime', required: false, displayName: 'Cooldown Until', description: 'Cooldown period end (30 days after release)' }
];

export interface SubdomainFormBaseProps {
  /** Form submission handler */
  onSubmit: (data: SubdomainCreate) => void | Promise<void>;
  /** Default values for the form */
  defaultValues?: Partial<SubdomainCreate>;
  /** Loading state */
  loading?: boolean;
  /** Submit button text */
  submitLabel?: string;
  /** Cancel handler */
  onCancel?: () => void;
}

/**
 * Base form component for creating/editing Subdomain.
 * Extend this in components/subdomain/SubdomainForm.tsx
 */
export function SubdomainFormBase({
  onSubmit,
  defaultValues,
  loading = false,
  submitLabel = 'Save',
  onCancel,
}: SubdomainFormBaseProps): ReactElement {
  const registry = useWidgetRegistry();
  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm<SubdomainCreate>({ defaultValues });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      {SUBDOMAIN_FIELD_SPECS.map((field) => {
        const Widget = registry.resolve(
          'Subdomain',
          field.name,
          field.type,
          field.uiWidget
        );

        return (
          <Controller
            key={field.name}
            name={field.name as keyof SubdomainCreate}
            control={control}
            rules={{ required: field.required }}
            render={({ field: { onChange, value } }) => (
              <Widget
                name={field.name}
                value={value}
                onChange={onChange}
                label={field.displayName ?? field.name}
                description={field.description}
                placeholder={field.placeholder}
                required={field.required}
                disabled={loading}
                error={errors[field.name as keyof SubdomainCreate]?.message}
                options={field.enumValues}
                references={field.references}
                {...field.widgetProps}
              />
            )}
          />
        );
      })}

      <div className="flex items-center justify-end gap-3 pt-4 border-t border-nordic-100">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            disabled={loading}
            className="btn-secondary"
          >
            Cancel
          </button>
        )}
        <button type="submit" disabled={loading} className="btn-primary">
          {loading ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Saving...
            </span>
          ) : submitLabel}
        </button>
      </div>
    </form>
  );
}
