"""GraphQL queries for AllowedEmailDomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from typing import Any

import strawberry
from strawberry.types import Info

from prisme_api.schemas.allowed_email_domain import AllowedEmailDomainFilter
from prisme_api.services.allowed_email_domain import AllowedEmailDomainService

from ..context import Context
from ..filters.allowed_email_domain import AllowedEmailDomainWhereInput
from ..pagination import Connection, OffsetPaginationInput, paginate_results
from ..types.allowed_email_domain import AllowedEmailDomainType, allowed_email_domain_from_model


@strawberry.type
class AllowedEmailDomainQueries:
    """GraphQL queries for AllowedEmailDomain."""

    @strawberry.field(description="Get a single AllowedEmailDomain by ID")
    async def allowedEmailDomain(
        self,
        info: Info[Context, None],
        id: int,
    ) -> AllowedEmailDomainType | None:
        """Get a AllowedEmailDomain by ID."""
        service = AllowedEmailDomainService(info.context.db)
        result = await service.get(id)
        if result is None:
            return None
        return allowed_email_domain_from_model(result)

    @strawberry.field(description="List allowed_email_domains with filtering and pagination")
    async def allowedEmailDomains(
        self,
        info: Info[Context, None],
        where: AllowedEmailDomainWhereInput | None = None,
        pagination: OffsetPaginationInput | None = None,
    ) -> Connection[AllowedEmailDomainType]:
        """List allowed_email_domains."""
        service = AllowedEmailDomainService(info.context.db)

        page = pagination.page if pagination else 1
        page_size = pagination.page_size if pagination else 20
        skip = (page - 1) * page_size

        # Convert GraphQL where input to service filter
        filters = _convert_where_to_filter(where) if where else None

        items = await service.list(skip=skip, limit=page_size, filters=filters)
        total = await service.count_filtered(filters=filters)

        typed_items = [allowed_email_domain_from_model(item) for item in items]
        return paginate_results(typed_items, total, page, page_size)


def _convert_where_to_filter(where: AllowedEmailDomainWhereInput) -> AllowedEmailDomainFilter:
    """Convert GraphQL where input to Pydantic filter schema."""
    filter_dict: dict[str, Any] = {}

    # Handle ID filter
    if where.id is not None:
        _apply_int_filter(filter_dict, "id", where.id)

    return AllowedEmailDomainFilter(**filter_dict)


def _apply_int_filter(filter_dict: dict[str, Any], field_name: str, filter_input: Any) -> None:
    """Apply an integer filter to the filter dictionary."""
    if filter_input.eq is not None:
        filter_dict[field_name] = filter_input.eq
    if filter_input.ne is not None:
        filter_dict[f"{field_name}_ne"] = filter_input.ne
    if filter_input.gt is not None:
        filter_dict[f"{field_name}_gt"] = filter_input.gt
    if filter_input.gte is not None:
        filter_dict[f"{field_name}_gte"] = filter_input.gte
    if filter_input.lt is not None:
        filter_dict[f"{field_name}_lt"] = filter_input.lt
    if filter_input.lte is not None:
        filter_dict[f"{field_name}_lte"] = filter_input.lte
    if filter_input.in_ is not None:
        filter_dict[f"{field_name}_in"] = filter_input.in_


__all__ = ["AllowedEmailDomainQueries"]
