"""Custom GraphQL scalars.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import strawberry

# Re-export built-in scalars
JSON = strawberry.scalars.JSON


__all__ = ["JSON"]
