/**
 * Tests for auth API client.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as authApi from '../../lib/authApi';

describe('authApi', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('calls signup', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'Check your email' }),
    } as Response);

    const result = await authApi.signup('a@b.com', 'user1', 'StrongPass1');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/signup', expect.objectContaining({
      method: 'POST',
    }));
    expect(result.message).toBeDefined();
  });

  it('calls login', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ requires_mfa: false, user: { id: 1 } }),
    } as Response);

    const result = await authApi.login('a@b.com', 'StrongPass1');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/login', expect.objectContaining({
      method: 'POST',
    }));
    expect(result.requires_mfa).toBe(false);
  });

  it('calls loginMFA', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ user: { id: 1, email: 'a@b.com' } }),
    } as Response);

    const result = await authApi.loginMFA('a@b.com', '123456');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/login/mfa', expect.objectContaining({
      method: 'POST',
    }));
    expect(result.user).toBeDefined();
  });

  it('calls setupMFA', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ totp_uri: 'otpauth://...', secret: 'abc' }),
    } as Response);

    const result = await authApi.setupMFA();
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/mfa/setup', expect.objectContaining({
      method: 'POST',
    }));
    expect(result.secret).toBeDefined();
  });

  it('calls verifyMFASetup', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'MFA enabled' }),
    } as Response);

    await authApi.verifyMFASetup('123456');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/mfa/verify-setup', expect.objectContaining({
      method: 'POST',
    }));
  });

  it('calls disableMFA', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'MFA disabled' }),
    } as Response);

    await authApi.disableMFA('password');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/mfa/disable', expect.objectContaining({
      method: 'POST',
    }));
  });

  it('calls verifyEmail', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'Email verified' }),
    } as Response);

    const result = await authApi.verifyEmail('token123');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/verify-email', expect.objectContaining({
      method: 'POST',
    }));
    expect(result.message).toBe('Email verified');
  });

  it('calls forgotPassword', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'ok' }),
    } as Response);

    await authApi.forgotPassword('a@b.com');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/forgot-password', expect.objectContaining({
      method: 'POST',
    }));
  });

  it('calls resetPassword', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'ok' }),
    } as Response);

    await authApi.resetPassword('token', 'NewPass1');
    expect(global.fetch).toHaveBeenCalledWith('/api/auth/reset-password', expect.objectContaining({
      method: 'POST',
    }));
  });

  it('throws on error response', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      json: () => Promise.resolve({ detail: 'Bad request' }),
    } as Response);

    await expect(authApi.login('a@b.com', 'bad')).rejects.toThrow();
  });
});
