/**
 * Tests for SignupForm component.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { AuthProvider } from '../../contexts/AuthContext';
import {{ SignupForm }} from '../../components/auth/SignupForm';

describe('SignupForm', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      status: 401,
      json: () => Promise.resolve({ detail: 'Not authenticated' }),
    } as Response);
  });

  it('renders signup fields', () => {
    render(
      <MemoryRouter>
        <AuthProvider>
          <SignupForm />
        </AuthProvider>
      </MemoryRouter>
    );

    expect(screen.getByLabelText(/email/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/username/i)).toBeInTheDocument();
  });

  it('shows password mismatch error', async () => {
    render(
      <MemoryRouter>
        <AuthProvider>
          <SignupForm />
        </AuthProvider>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getByLabelText(/email/i)).toBeInTheDocument();
    });

    const passwordFields = screen.getAllByLabelText(/password/i);
    await userEvent.type(passwordFields[0], 'StrongPass1');
    if (passwordFields.length > 1) {
      await userEvent.type(passwordFields[1], 'Different1');
    }
    await userEvent.click(screen.getByRole('button', { name: /sign up|create/i }));

    await waitFor(() => {
      const errorEl = screen.queryByText(/match|mismatch/i);
      // Only assert if confirm password field exists
      if (passwordFields.length > 1) {
        expect(errorEl).toBeInTheDocument();
      }
    });
  });

  it('submits signup', async () => {
    const signupFetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ message: 'Check your email' }),
    } as Response);

    global.fetch = vi.fn()
      .mockResolvedValueOnce({
        ok: false,
        status: 401,
        json: () => Promise.resolve({ detail: 'Not authenticated' }),
      } as Response)
      .mockImplementation(signupFetch);

    render(
      <MemoryRouter>
        <AuthProvider>
          <SignupForm />
        </AuthProvider>
      </MemoryRouter>
    );

    await waitFor(() => {
      expect(screen.getByLabelText(/email/i)).toBeInTheDocument();
    });

    await userEvent.type(screen.getByLabelText(/email/i), 'new@example.com');
    await userEvent.type(screen.getByLabelText(/username/i), 'newuser');
    const passwordFields = screen.getAllByLabelText(/password/i);
    await userEvent.type(passwordFields[0], 'StrongPass1');
    if (passwordFields.length > 1) {
      await userEvent.type(passwordFields[1], 'StrongPass1');
    }
    await userEvent.click(screen.getByRole('button', { name: /sign up|create/i }));

    await waitFor(() => {
      expect(signupFetch).toHaveBeenCalled();
    });
  });
});
