"""GraphQL tests for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest
from tests.factories.subdomain import SubdomainFactory


class TestSubdomainGraphQL:
    """GraphQL tests for Subdomain queries and mutations."""

    @pytest.mark.asyncio
    async def test_query_subdomain(self, client, db):
        """Test subdomain query."""
        SubdomainFactory._meta.sqlalchemy_session = db
        instance = SubdomainFactory.create()
        await db.commit()

        query = """
            query GetSubdomain($id: Int!) {
                subdomain(id: $id) {
                    id
                }
            }
        """

        response = await client.post(
            "/graphql",
            json={"query": query, "variables": {"id": instance.id}},
        )

        assert response.status_code == 200
        data = response.json()
        assert "data" in data
        assert data["data"]["subdomain"] is not None, (
            f"Query returned None. Errors: {data.get('errors')}"
        )
        assert data["data"]["subdomain"]["id"] == instance.id

    @pytest.mark.asyncio
    async def test_query_subdomains_list(self, client, db):
        """Test subdomains list query."""
        SubdomainFactory._meta.sqlalchemy_session = db
        for _ in range(3):
            SubdomainFactory.create()
        await db.commit()

        query = """
            query ListSubdomains {
                subdomains {
                    edges {
                        node {
                            id
                        }
                    }
                    totalCount
                }
            }
        """

        response = await client.post("/graphql", json={"query": query})

        assert response.status_code == 200
        data = response.json()
        assert "data" in data
        assert data["data"]["subdomains"]["totalCount"] >= 3
