"""GraphQL tests for AllowedEmailDomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest
from tests.factories.allowed_email_domain import AllowedEmailDomainFactory


class TestAllowedEmailDomainGraphQL:
    """GraphQL tests for AllowedEmailDomain queries and mutations."""

    @pytest.mark.asyncio
    async def test_query_allowed_email_domain(self, client, db):
        """Test allowedEmailDomain query."""
        AllowedEmailDomainFactory._meta.sqlalchemy_session = db
        instance = AllowedEmailDomainFactory.create()
        await db.commit()

        query = """
            query GetAllowedEmailDomain($id: Int!) {
                allowedEmailDomain(id: $id) {
                    id
                }
            }
        """

        response = await client.post(
            "/graphql",
            json={"query": query, "variables": {"id": instance.id}},
        )

        assert response.status_code == 200
        data = response.json()
        assert "data" in data
        assert data["data"]["allowedEmailDomain"] is not None, (
            f"Query returned None. Errors: {data.get('errors')}"
        )
        assert data["data"]["allowedEmailDomain"]["id"] == instance.id

    @pytest.mark.asyncio
    async def test_query_allowed_email_domains_list(self, client, db):
        """Test allowedEmailDomains list query."""
        AllowedEmailDomainFactory._meta.sqlalchemy_session = db
        for _ in range(3):
            AllowedEmailDomainFactory.create()
        await db.commit()

        query = """
            query ListAllowedEmailDomains {
                allowedEmailDomains {
                    edges {
                        node {
                            id
                        }
                    }
                    totalCount
                }
            }
        """

        response = await client.post("/graphql", json={"query": query})

        assert response.status_code == 200
        data = response.json()
        assert "data" in data
        assert data["data"]["allowedEmailDomains"]["totalCount"] >= 3
