"""GraphQL tests for APIKey.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import pytest
from tests.factories.api_key import APIKeyFactory


class TestAPIKeyGraphQL:
    """GraphQL tests for APIKey queries and mutations."""

    @pytest.mark.asyncio
    async def test_query_api_key(self, client, db):
        """Test apikey query."""
        APIKeyFactory._meta.sqlalchemy_session = db
        instance = APIKeyFactory.create()
        await db.commit()

        query = """
            query GetAPIKey($id: Int!) {
                apikey(id: $id) {
                    id
                }
            }
        """

        response = await client.post(
            "/graphql",
            json={"query": query, "variables": {"id": instance.id}},
        )

        assert response.status_code == 200
        data = response.json()
        assert "data" in data
        assert data["data"]["apikey"] is not None, (
            f"Query returned None. Errors: {data.get('errors')}"
        )
        assert data["data"]["apikey"]["id"] == instance.id

    @pytest.mark.asyncio
    async def test_query_api_keys_list(self, client, db):
        """Test apiKeys list query."""
        APIKeyFactory._meta.sqlalchemy_session = db
        for _ in range(3):
            APIKeyFactory.create()
        await db.commit()

        query = """
            query ListAPIKeys {
                apiKeys {
                    edges {
                        node {
                            id
                        }
                    }
                    totalCount
                }
            }
        """

        response = await client.post("/graphql", json={"query": query})

        assert response.status_code == 200
        data = response.json()
        assert "data" in data
        assert data["data"]["apiKeys"]["totalCount"] >= 3
