"""REST API routes for APIKey.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
Extend this router in api/rest/api_key.py
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, HTTPException, Query, status

from prisme_api.schemas.api_key import (
    APIKeyCreate,
    APIKeyRead,
    APIKeyUpdate,
)
from prisme_api.schemas.base import PaginatedResponse
from prisme_api.services.api_key import APIKeyService

from .deps import DbSession, Pagination, Sorting

router = APIRouter(prefix="/api-keys", tags=["api-keys"])


@router.get(
    "",
    response_model=PaginatedResponse[APIKeyRead],
    summary="List api_keys",
)
async def list_api_keys(
    db: DbSession,
    pagination: Pagination,
    sorting: Sorting,
    include_deleted: Annotated[bool, Query(description="Include soft-deleted records")] = False,
) -> PaginatedResponse[APIKeyRead]:
    """List api_keys with pagination and filtering."""
    service = APIKeyService(db)

    items = await service.list(
        skip=pagination.skip,
        limit=pagination.limit,
        sort_by=sorting.sort_by,
        sort_order=sorting.sort_order,
        include_deleted=include_deleted,
    )

    total = await service.count(include_deleted=include_deleted)
    pages = (total + pagination.page_size - 1) // pagination.page_size

    return PaginatedResponse(
        items=[APIKeyRead.model_validate(item) for item in items],
        total=total,
        page=pagination.page,
        page_size=pagination.page_size,
        pages=pages,
    )


@router.get(
    "/{id}",
    response_model=APIKeyRead,
    summary="Get api_key",
)
async def get_api_key(
    db: DbSession,
    id: int,
) -> APIKeyRead:
    """Get a api_key by ID."""
    service = APIKeyService(db)

    result = await service.get(id)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="APIKey not found",
        )

    return APIKeyRead.model_validate(result)


@router.post(
    "",
    response_model=APIKeyRead,
    status_code=status.HTTP_201_CREATED,
    summary="Create api_key",
)
async def create_api_key(
    db: DbSession,
    data: APIKeyCreate,
) -> APIKeyRead:
    """Create a new api_key."""
    service = APIKeyService(db)

    result = await service.create(data=data)
    return APIKeyRead.model_validate(result)


@router.patch(
    "/{id}",
    response_model=APIKeyRead,
    summary="Update api_key",
)
async def update_api_key(
    db: DbSession,
    id: int,
    data: APIKeyUpdate,
) -> APIKeyRead:
    """Update a api_key."""
    service = APIKeyService(db)

    result = await service.update(id=id, data=data)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="APIKey not found",
        )

    return APIKeyRead.model_validate(result)


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete api_key",
)
async def delete_api_key(
    db: DbSession,
    id: int,
    hard: Annotated[bool, Query(description="Permanently delete")] = False,
) -> None:
    """Delete a api_key."""
    service = APIKeyService(db)

    success = await service.delete(id=id, soft=not hard and False)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="APIKey not found",
        )


@router.post(
    "/bulk",
    response_model=list[APIKeyRead],
    status_code=status.HTTP_201_CREATED,
    summary="Bulk create api_keys",
)
async def bulk_create_api_keys(
    db: DbSession,
    data: list[APIKeyCreate],
) -> list[APIKeyRead]:
    """Create multiple api_keys in a single request."""
    service = APIKeyService(db)

    results = await service.create_many(data=data)
    return [APIKeyRead.model_validate(item) for item in results]


@router.patch(
    "/bulk",
    summary="Bulk update api_keys",
)
async def bulk_update_api_keys(
    db: DbSession,
    ids: Annotated[list[int], Query(description="IDs to update")],
    data: APIKeyUpdate,
) -> dict[str, int]:
    """Update multiple api_keys with the same data."""
    service = APIKeyService(db)

    count = await service.update_many(ids=ids, data=data)
    return {"updated": count}


@router.delete(
    "/bulk",
    summary="Bulk delete api_keys",
)
async def bulk_delete_api_keys(
    db: DbSession,
    ids: Annotated[list[int], Query(description="IDs to delete")],
    hard: Annotated[bool, Query(description="Permanently delete")] = False,
) -> dict[str, int]:
    """Delete multiple api_keys."""
    service = APIKeyService(db)

    count = await service.delete_many(ids=ids, soft=not hard and False)
    return {"deleted": count}


__all__ = ["router"]
