"""REST API routes for User.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
Extend this router in api/rest/user.py
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, HTTPException, Query, status

from prisme_api.schemas.base import PaginatedResponse
from prisme_api.schemas.user import (
    UserCreate,
    UserRead,
    UserUpdate,
)
from prisme_api.services.user import UserService

from .deps import DbSession, Pagination, Sorting

router = APIRouter(prefix="/users", tags=["users"])


@router.get(
    "",
    response_model=PaginatedResponse[UserRead],
    summary="List users",
)
async def list_users(
    db: DbSession,
    pagination: Pagination,
    sorting: Sorting,
    include_deleted: Annotated[bool, Query(description="Include soft-deleted records")] = False,
) -> PaginatedResponse[UserRead]:
    """List users with pagination and filtering."""
    service = UserService(db)

    items = await service.list(
        skip=pagination.skip,
        limit=pagination.limit,
        sort_by=sorting.sort_by,
        sort_order=sorting.sort_order,
        include_deleted=include_deleted,
    )

    total = await service.count(include_deleted=include_deleted)
    pages = (total + pagination.page_size - 1) // pagination.page_size

    return PaginatedResponse(
        items=[UserRead.model_validate(item) for item in items],
        total=total,
        page=pagination.page,
        page_size=pagination.page_size,
        pages=pages,
    )


@router.get(
    "/{id}",
    response_model=UserRead,
    summary="Get user",
)
async def get_user(
    db: DbSession,
    id: int,
) -> UserRead:
    """Get a user by ID."""
    service = UserService(db)

    result = await service.get(id)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    return UserRead.model_validate(result)


@router.post(
    "",
    response_model=UserRead,
    status_code=status.HTTP_201_CREATED,
    summary="Create user",
)
async def create_user(
    db: DbSession,
    data: UserCreate,
) -> UserRead:
    """Create a new user."""
    service = UserService(db)

    result = await service.create(data=data)
    return UserRead.model_validate(result)


@router.patch(
    "/{id}",
    response_model=UserRead,
    summary="Update user",
)
async def update_user(
    db: DbSession,
    id: int,
    data: UserUpdate,
) -> UserRead:
    """Update a user."""
    service = UserService(db)

    result = await service.update(id=id, data=data)
    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    return UserRead.model_validate(result)


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete user",
)
async def delete_user(
    db: DbSession,
    id: int,
    hard: Annotated[bool, Query(description="Permanently delete")] = False,
) -> None:
    """Delete a user."""
    service = UserService(db)

    success = await service.delete(id=id, soft=not hard and True)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )


@router.post(
    "/bulk",
    response_model=list[UserRead],
    status_code=status.HTTP_201_CREATED,
    summary="Bulk create users",
)
async def bulk_create_users(
    db: DbSession,
    data: list[UserCreate],
) -> list[UserRead]:
    """Create multiple users in a single request."""
    service = UserService(db)

    results = await service.create_many(data=data)
    return [UserRead.model_validate(item) for item in results]


@router.patch(
    "/bulk",
    summary="Bulk update users",
)
async def bulk_update_users(
    db: DbSession,
    ids: Annotated[list[int], Query(description="IDs to update")],
    data: UserUpdate,
) -> dict[str, int]:
    """Update multiple users with the same data."""
    service = UserService(db)

    count = await service.update_many(ids=ids, data=data)
    return {"updated": count}


@router.delete(
    "/bulk",
    summary="Bulk delete users",
)
async def bulk_delete_users(
    db: DbSession,
    ids: Annotated[list[int], Query(description="IDs to delete")],
    hard: Annotated[bool, Query(description="Permanently delete")] = False,
) -> dict[str, int]:
    """Delete multiple users."""
    service = UserService(db)

    count = await service.delete_many(ids=ids, soft=not hard and True)
    return {"deleted": count}


__all__ = ["router"]
