/**
 * React Router configuration with Nordic-styled layout.
 *
 * ⚠️ AUTO-GENERATED BY PRISM
 * Generated sections will be updated on `prism generate`.
 * Add custom code inside PRISM:PROTECTED regions to preserve it.
 */

import { useEffect, type ReactElement } from 'react';
import { createBrowserRouter, Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { Login } from './pages/Login';
import { Signup } from './pages/Signup';
import UsersListPage from './pages/users';
import UserDetailPage from './pages/users/[id]';
import UserCreatePage from './pages/users/new';
import UserEditPage from './pages/users/[id]/edit';
import APIKeysListPage from './pages/api-keys';
import APIKeyDetailPage from './pages/api-keys/[id]';
import APIKeyCreatePage from './pages/api-keys/new';
import APIKeyEditPage from './pages/api-keys/[id]/edit';
import SubdomainsListPage from './pages/subdomains';
import SubdomainDetailPage from './pages/subdomains/[id]';
import SubdomainCreatePage from './pages/subdomains/new';
import SubdomainEditPage from './pages/subdomains/[id]/edit';
import { useAuth } from './contexts/AuthContext';

// PRISM:PROTECTED:START - Custom Imports
// Add your custom page imports here:
// import MyCustomPage from './pages/custom';
// PRISM:PROTECTED:END

/** App name and description for branding */
const APP_NAME = "MadeWithPris.me API";
const APP_INITIAL = "M";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _APP_DESCRIPTION = "Managed subdomain service for madewithpris.me";

/** Shared layout with sidebar navigation */
function Layout({ children }: { children?: React.ReactNode }): ReactElement {
  const location = useLocation();  const { user, isAuthenticated, logout } = useAuth();
  // Update document title based on route
  useEffect(() => {
    const path = location.pathname;
    let title = APP_NAME;
    if (path !== '/') {
      const segment = path.split('/').filter(Boolean)[0];
      if (segment) {
        title = `${segment.charAt(0).toUpperCase() + segment.slice(1)} | ${APP_NAME}`;
      }
    }
    document.title = title;
  }, [location]);

  return (
    <div className="min-h-screen bg-nordic-50">
      {/* Sidebar */}
      <aside className="fixed inset-y-0 left-0 w-64 bg-white border-r border-nordic-200">
        <div className="flex flex-col h-full">
          {/* Logo */}
          <div className="flex items-center h-16 px-6 border-b border-nordic-100">
            <Link to="/" className="flex items-center gap-2">
              <div className="w-8 h-8 bg-nordic-900 rounded-nordic flex items-center justify-center">
                <span className="text-white font-bold text-sm">{APP_INITIAL}</span>
              </div>
              <span className="font-semibold text-nordic-900">{APP_NAME}</span>
            </Link>
          </div>

          {/* Navigation */}
          <nav className="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
          <NavLink
            to="/users"
            className={({ isActive }) =>
              `flex items-center gap-3 px-3 py-2 rounded-nordic text-sm font-medium transition-colors ${
                isActive
                  ? 'bg-nordic-100 text-nordic-900'
                  : 'text-nordic-600 hover:bg-nordic-50 hover:text-nordic-900'
              }`
            }
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
            Users
          </NavLink>
          <NavLink
            to="/api-keys"
            className={({ isActive }) =>
              `flex items-center gap-3 px-3 py-2 rounded-nordic text-sm font-medium transition-colors ${
                isActive
                  ? 'bg-nordic-100 text-nordic-900'
                  : 'text-nordic-600 hover:bg-nordic-50 hover:text-nordic-900'
              }`
            }
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
            APIKeys
          </NavLink>
          <NavLink
            to="/subdomains"
            className={({ isActive }) =>
              `flex items-center gap-3 px-3 py-2 rounded-nordic text-sm font-medium transition-colors ${
                isActive
                  ? 'bg-nordic-100 text-nordic-900'
                  : 'text-nordic-600 hover:bg-nordic-50 hover:text-nordic-900'
              }`
            }
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
            Subdomains
          </NavLink>
            {/* PRISM:PROTECTED:START - Custom Nav Links */}
            {/* Add your custom navigation links here */}
            {/* PRISM:PROTECTED:END */}
          </nav>

          {/* Footer */}
          <div className="p-4 border-t border-nordic-100">
{isAuthenticated && user ? (
              <div className="space-y-2">
                <div className="flex items-center gap-2 px-2">
                  <div className="w-8 h-8 bg-nordic-100 rounded-full flex items-center justify-center">
                    <span className="text-nordic-600 text-xs font-medium">
                      {((user as any).email || (user as any).username || "U").charAt(0).toUpperCase()}
                    </span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-medium text-nordic-900 truncate">
                      {(user as any).email || (user as any).username || "User"}
                    </p>
                  </div>
                </div>
                <button
                  onClick={logout}
                  className="w-full px-2 py-1.5 text-xs text-nordic-600 hover:text-nordic-900 hover:bg-nordic-50 rounded transition-colors text-left"
                >
                  Sign out
                </button>
              </div>
            ) : (
              <p className="text-xs text-nordic-400 text-center">
                Built with Prism
              </p>
            )}          </div>
        </div>
      </aside>

      {/* Main content */}
      <main className="pl-64">
        {children}
        <Outlet />
      </main>
    </div>
  );
}

/** Home page with welcome message */
function HomePage(): ReactElement {
  return (
    <div className="page-container">
      <div className="card p-8 text-center">
        <div className="w-16 h-16 bg-nordic-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <svg className="w-8 h-8 text-nordic-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
        </div>
        <h1 className="text-2xl font-semibold text-nordic-900 mb-2">Welcome</h1>
        <p className="text-nordic-500 max-w-md mx-auto">
          Select an item from the sidebar to get started.
        </p>
      </div>
    </div>
  );
}

/** Application router with all model routes */
export const router = createBrowserRouter([
  {
    element: <Layout />,
    children: [
      { path: '/', element: <HomePage /> },
  { path: '/login', element: <Login /> },
  { path: '/signup', element: <Signup /> },
  { path: '/users', element: <UsersListPage /> },
  { path: '/users/:id', element: <UserDetailPage /> },
  { path: '/users/new', element: <UserCreatePage /> },
  { path: '/users/:id/edit', element: <UserEditPage /> },
  { path: '/api-keys', element: <APIKeysListPage /> },
  { path: '/api-keys/:id', element: <APIKeyDetailPage /> },
  { path: '/api-keys/new', element: <APIKeyCreatePage /> },
  { path: '/api-keys/:id/edit', element: <APIKeyEditPage /> },
  { path: '/subdomains', element: <SubdomainsListPage /> },
  { path: '/subdomains/:id', element: <SubdomainDetailPage /> },
  { path: '/subdomains/new', element: <SubdomainCreatePage /> },
  { path: '/subdomains/:id/edit', element: <SubdomainEditPage /> },
      // PRISM:PROTECTED:START - Custom Routes
      // Add your custom routes here:
      // { path: '/custom', element: <MyCustomPage /> },
      // PRISM:PROTECTED:END
    ],
  },
]);

export default router;
