"""GraphQL types for APIKey.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

import datetime
from typing import TYPE_CHECKING, Annotated, Any

import strawberry
from strawberry.types import Info

if TYPE_CHECKING:
    from .user import UserType


@strawberry.type(description="API keys for user authentication")
class APIKeyType:
    """GraphQL type for APIKey."""

    id: int
    userId: int = strawberry.field(description="The user who owns this API key")
    keyHash: str = strawberry.field(description="Hashed API key (SHA256)")
    keyPrefix: str = strawberry.field(
        description="API key prefix for identification (e.g., prisme_live_sk_xxx)"
    )
    name: str = strawberry.field(description="Human-readable name for the API key")
    lastUsedAt: datetime.datetime | None = strawberry.field(
        description="Last time this API key was used"
    )
    expiresAt: datetime.datetime | None = strawberry.field(
        description="When this API key expires (null = never)"
    )
    isActive: bool = strawberry.field(description="Whether this API key is active")
    createdAt: datetime.datetime
    updatedAt: datetime.datetime

    # Private fields for relationship lazy loading
    _db_user: strawberry.Private[Any] = None

    # Relationship resolvers

    @strawberry.field
    async def user(self, info: Info) -> Annotated["UserType", strawberry.lazy(".user")] | None:
        """Fetch related User entities."""
        from .user import user_from_model

        if self._db_user is None:
            return None
        return user_from_model(self._db_user)


@strawberry.input(description="Input for creating a APIKey")
class APIKeyInput:
    """Input type for creating APIKey."""

    userId: int
    keyHash: str
    keyPrefix: str
    name: str
    lastUsedAt: datetime.datetime | None = None
    expiresAt: datetime.datetime | None = None
    isActive: bool = True


@strawberry.input(description="Input for updating a APIKey")
class APIKeyUpdateInput:
    """Input type for updating APIKey. All fields are optional."""

    userId: int | None = None
    keyHash: str | None = None
    keyPrefix: str | None = None
    name: str | None = None
    lastUsedAt: datetime.datetime | None = None
    expiresAt: datetime.datetime | None = None
    isActive: bool | None = None


def api_key_from_model(obj: Any) -> APIKeyType:
    """Convert a SQLAlchemy model to GraphQL type."""
    return APIKeyType(
        id=obj.id,
        userId=obj.user_id,
        keyHash=obj.key_hash,
        keyPrefix=obj.key_prefix,
        name=obj.name,
        lastUsedAt=obj.last_used_at,
        expiresAt=obj.expires_at,
        isActive=obj.is_active,
        createdAt=obj.created_at,
        updatedAt=obj.updated_at,
        _db_user=obj.__dict__.get("user"),
    )


__all__ = ["APIKeyInput", "APIKeyType", "APIKeyUpdateInput", "api_key_from_model"]
