"""GraphQL types for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

import datetime
from typing import Annotated, Any

import strawberry
from strawberry.types import Info


@strawberry.type(description="A managed madewithpris.me subdomain")
class SubdomainType:
    """GraphQL type for Subdomain."""

    id: int
    name: str = strawberry.field(description="Subdomain name (e.g., 'myapp')")
    ownerId: int | None = strawberry.field(description="The user who owns this subdomain")
    ipAddress: str | None = strawberry.field(description="IPv4 address for the A record")
    status: str = strawberry.field(description="Current status of the subdomain")
    dnsRecordId: str | None = strawberry.field(description="Hetzner DNS record ID")
    createdAt: datetime.datetime
    updatedAt: datetime.datetime

    # Private fields for relationship lazy loading
    _db_owner: strawberry.Private[Any] = None

    # Relationship resolvers

    @strawberry.field
    async def owner(
        self, info: Info
    ) -> (
        Annotated["UserType", strawberry.lazy("prisme_api.api.graphql._generated.types.user")]
        | None
    ):
        """Fetch related User entities."""
        from .user import user_from_model

        if self._db_owner is None:
            return None
        return user_from_model(self._db_owner)


@strawberry.input(description="Input for creating a Subdomain")
class SubdomainInput:
    """Input type for creating Subdomain."""

    name: str
    ownerId: int | None = None
    ipAddress: str | None = None
    status: str = "reserved"
    dnsRecordId: str | None = None


@strawberry.input(description="Input for updating a Subdomain")
class SubdomainUpdateInput:
    """Input type for updating Subdomain. All fields are optional."""

    name: str | None = None
    ownerId: int | None = None
    ipAddress: str | None = None
    status: str | None = None
    dnsRecordId: str | None = None


def subdomain_from_model(obj: Any) -> SubdomainType:
    """Convert a SQLAlchemy model to GraphQL type."""
    return SubdomainType(
        id=obj.id,
        name=obj.name,
        ownerId=obj.owner_id,
        ipAddress=obj.ip_address,
        status=obj.status,
        dnsRecordId=obj.dns_record_id,
        createdAt=obj.created_at,
        updatedAt=obj.updated_at,
        _db_owner=obj.__dict__.get("owner"),
    )


__all__ = ["SubdomainInput", "SubdomainType", "SubdomainUpdateInput", "subdomain_from_model"]
