"""GraphQL types for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

import datetime
from typing import TYPE_CHECKING, Annotated, Any

import strawberry
from strawberry.types import Info

if TYPE_CHECKING:
    from .user import UserType


@strawberry.type(description="A managed madewithpris.me subdomain")
class SubdomainType:
    """GraphQL type for Subdomain."""

    id: int
    name: str = strawberry.field(description="Subdomain name (e.g., 'myapp')")
    ownerId: int | None = strawberry.field(description="The user who owns this subdomain")
    ipAddress: str | None = strawberry.field(description="IPv4 address for the A record")
    status: str = strawberry.field(description="Current status of the subdomain")
    dnsRecordId: str | None = strawberry.field(description="Hetzner DNS record ID")
    port: int = strawberry.field(description="Target port for routing (default: 80)")
    releasedAt: datetime.datetime | None = strawberry.field(
        description="When the subdomain was released"
    )
    cooldownUntil: datetime.datetime | None = strawberry.field(
        description="Cooldown period end (30 days after release)"
    )
    createdAt: datetime.datetime
    updatedAt: datetime.datetime

    # Private fields for relationship lazy loading
    _db_owner: strawberry.Private[Any] = None

    # Relationship resolvers

    @strawberry.field
    async def owner(self, info: Info) -> Annotated["UserType", strawberry.lazy(".user")] | None:
        """Fetch related User entities."""
        from .user import user_from_model

        if self._db_owner is None:
            return None
        return user_from_model(self._db_owner)


@strawberry.input(description="Input for creating a Subdomain")
class SubdomainInput:
    """Input type for creating Subdomain."""

    name: str
    ownerId: int | None = None
    ipAddress: str | None = None
    status: str = "reserved"
    dnsRecordId: str | None = None
    port: int = 80
    releasedAt: datetime.datetime | None = None
    cooldownUntil: datetime.datetime | None = None


@strawberry.input(description="Input for updating a Subdomain")
class SubdomainUpdateInput:
    """Input type for updating Subdomain. All fields are optional."""

    name: str | None = None
    ownerId: int | None = None
    ipAddress: str | None = None
    status: str | None = None
    dnsRecordId: str | None = None
    port: int | None = None
    releasedAt: datetime.datetime | None = None
    cooldownUntil: datetime.datetime | None = None


def subdomain_from_model(obj: Any) -> SubdomainType:
    """Convert a SQLAlchemy model to GraphQL type."""
    return SubdomainType(
        id=obj.id,
        name=obj.name,
        ownerId=obj.owner_id,
        ipAddress=obj.ip_address,
        status=obj.status,
        dnsRecordId=obj.dns_record_id,
        port=obj.port,
        releasedAt=obj.released_at,
        cooldownUntil=obj.cooldown_until,
        createdAt=obj.created_at,
        updatedAt=obj.updated_at,
        _db_owner=obj.__dict__.get("owner"),
    )


__all__ = ["SubdomainInput", "SubdomainType", "SubdomainUpdateInput", "subdomain_from_model"]
