/**
 * useAllowedEmailDomainFormState Hook
 *
 * A typed form state hook for AllowedEmailDomain that provides:
 * - Type-safe form values
 * - Field-level validation
 * - Dirty/touched tracking
 * - Reset/submit helpers
 *
 * @example
 * ```tsx
 * const form = useAllowedEmailDomainFormState({
 *   initialValues: allowedEmailDomain ?? undefined,
 *   onSubmit: async (values) => {
 *     if (allowedEmailDomain) {
 *       await mutations.update(allowedEmailDomain.id, values);
 *     } else {
 *       await mutations.create(values);
 *     }
 *   },
 * });
 *
 * return (
 *   <form onSubmit={form.handleSubmit}>
 *     <input
 *       name="name"
 *       value={form.values.name}
 *       onChange={(e) => form.setValue('name', e.target.value)}
 *       onBlur={() => form.setTouched('name')}
 *     />
 *     {form.touched.name && form.errors.name && (
 *       <span className="error">{form.errors.name}</span>
 *     )}
 *     <button type="submit" disabled={form.isSubmitting || !form.isValid}>
 *       {form.isSubmitting ? 'Saving...' : 'Save'}
 *     </button>
 *   </form>
 * );
 * ```
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { useState, useCallback, useMemo } from 'react';
import type {
  AllowedEmailDomain,
  AllowedEmailDomainCreate,
  AllowedEmailDomainUpdate,
} from '../types/generated';

// ============================================================================
// Types
// ============================================================================

/** Form values type (same as create input) */
export type AllowedEmailDomainFormValues = AllowedEmailDomainCreate;

/** Form errors - partial record of field to error message */
export type AllowedEmailDomainFormErrors = Partial<Record<keyof AllowedEmailDomainFormValues, string>>;

/** Touched state - which fields have been touched */
export type AllowedEmailDomainFormTouched = Partial<Record<keyof AllowedEmailDomainFormValues, boolean>>;

/** Validation function type */
export type AllowedEmailDomainValidator = (
  values: Partial<AllowedEmailDomainFormValues>
) => AllowedEmailDomainFormErrors;

/** Form state hook options */
export interface UseAllowedEmailDomainFormStateOptions {
  /** Initial form values (for edit mode) */
  initialValues?: Partial<AllowedEmailDomainFormValues>;
  /** Custom validation function */
  validate?: AllowedEmailDomainValidator;
  /** Submit handler */
  onSubmit?: (values: AllowedEmailDomainFormValues) => Promise<void> | void;
  /** Whether to validate on change */
  validateOnChange?: boolean;
  /** Whether to validate on blur */
  validateOnBlur?: boolean;
}

/** Form state */
export interface AllowedEmailDomainFormState {
  /** Current form values */
  values: Partial<AllowedEmailDomainFormValues>;
  /** Validation errors */
  errors: AllowedEmailDomainFormErrors;
  /** Which fields have been touched */
  touched: AllowedEmailDomainFormTouched;
  /** Whether form is currently submitting */
  isSubmitting: boolean;
  /** Whether form has been modified from initial values */
  isDirty: boolean;
  /** Whether form has any validation errors */
  isValid: boolean;
  /** Whether form has been submitted at least once */
  isSubmitted: boolean;
}

/** Form actions */
export interface AllowedEmailDomainFormActions {
  /** Set a single field value */
  setValue: <K extends keyof AllowedEmailDomainFormValues>(
    field: K,
    value: AllowedEmailDomainFormValues[K]
  ) => void;
  /** Set multiple field values */
  setValues: (values: Partial<AllowedEmailDomainFormValues>) => void;
  /** Mark a field as touched */
  setTouched: (field: keyof AllowedEmailDomainFormValues) => void;
  /** Set a field error manually */
  setError: (field: keyof AllowedEmailDomainFormValues, message: string | undefined) => void;
  /** Validate the form and return errors */
  validate: () => AllowedEmailDomainFormErrors;
  /** Reset form to initial values */
  reset: (newInitialValues?: Partial<AllowedEmailDomainFormValues>) => void;
  /** Handle form submission */
  handleSubmit: (e?: React.FormEvent) => Promise<void>;
  /** Get props for an input field */
  getFieldProps: (field: keyof AllowedEmailDomainFormValues) => {
    name: string;
    value: unknown;
    onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => void;
    onBlur: () => void;
  };
}

/** Combined form state and actions */
export type UseAllowedEmailDomainFormStateResult = AllowedEmailDomainFormState & AllowedEmailDomainFormActions;

// ============================================================================
// Default Validation
// ============================================================================

/**
 * Default validation based on field specs.
 * Override with custom validate function if needed.
 */
function defaultValidate(values: Partial<AllowedEmailDomainFormValues>): AllowedEmailDomainFormErrors {
  const errors: AllowedEmailDomainFormErrors = {};  // domain is required
  if (values.domain === undefined || values.domain === null || values.domain === '') {
    errors.domain = 'Domain is required';
  }  // domain max length
  if (typeof values.domain === 'string' && values.domain.length > 255) {
    errors.domain = 'Domain must be 255 characters or less';
  }  // description max length
  if (typeof values.description === 'string' && values.description.length > 500) {
    errors.description = 'Description must be 500 characters or less';
  }
  return errors;
}

// ============================================================================
// Hook Implementation
// ============================================================================

/**
 * Hook for managing AllowedEmailDomain form state.
 *
 * @param options - Form state options
 * @returns Form state and actions
 */
export function useAllowedEmailDomainFormState(
  options: UseAllowedEmailDomainFormStateOptions = {}
): UseAllowedEmailDomainFormStateResult {
  const {
    initialValues = {},
    validate = defaultValidate,
    onSubmit,
    validateOnChange = false,
    validateOnBlur = true,
  } = options;

  // State
  const [values, setValuesState] = useState<Partial<AllowedEmailDomainFormValues>>(initialValues);
  const [errors, setErrors] = useState<AllowedEmailDomainFormErrors>({});
  const [touched, setTouchedState] = useState<AllowedEmailDomainFormTouched>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [initialValuesState, setInitialValuesState] = useState<Partial<AllowedEmailDomainFormValues>>(initialValues);

  // Computed state
  const isDirty = useMemo(() => {
    return JSON.stringify(values) !== JSON.stringify(initialValuesState);
  }, [values, initialValuesState]);

  const isValid = useMemo(() => {
    const validationErrors = validate(values);
    return Object.keys(validationErrors).length === 0;
  }, [values, validate]);

  // Actions
  const setValue = useCallback(
    <K extends keyof AllowedEmailDomainFormValues>(field: K, value: AllowedEmailDomainFormValues[K]) => {
      setValuesState((prev) => ({ ...prev, [field]: value }));
      if (validateOnChange) {
        const newValues = { ...values, [field]: value };
        const newErrors = validate(newValues);
        setErrors(newErrors);
      }
    },
    [values, validate, validateOnChange]
  );

  const setValues = useCallback(
    (newValues: Partial<AllowedEmailDomainFormValues>) => {
      setValuesState((prev) => ({ ...prev, ...newValues }));
      if (validateOnChange) {
        const merged = { ...values, ...newValues };
        const newErrors = validate(merged);
        setErrors(newErrors);
      }
    },
    [values, validate, validateOnChange]
  );

  const setTouched = useCallback(
    (field: keyof AllowedEmailDomainFormValues) => {
      setTouchedState((prev) => ({ ...prev, [field]: true }));
      if (validateOnBlur) {
        const newErrors = validate(values);
        setErrors(newErrors);
      }
    },
    [values, validate, validateOnBlur]
  );

  const setError = useCallback(
    (field: keyof AllowedEmailDomainFormValues, message: string | undefined) => {
      setErrors((prev) => {
        if (message === undefined) {
          const { [field]: _, ...rest } = prev;
          return rest;
        }
        return { ...prev, [field]: message };
      });
    },
    []
  );

  const validateForm = useCallback((): AllowedEmailDomainFormErrors => {
    const newErrors = validate(values);
    setErrors(newErrors);
    return newErrors;
  }, [values, validate]);

  const reset = useCallback(
    (newInitialValues?: Partial<AllowedEmailDomainFormValues>) => {
      const resetValues = newInitialValues ?? initialValuesState;
      setValuesState(resetValues);
      setErrors({});
      setTouchedState({});
      setIsSubmitting(false);
      setIsSubmitted(false);
      if (newInitialValues) {
        setInitialValuesState(newInitialValues);
      }
    },
    [initialValuesState]
  );

  const handleSubmit = useCallback(
    async (e?: React.FormEvent) => {
      e?.preventDefault();
      setIsSubmitted(true);

      // Mark all fields as touched
      const allTouched: AllowedEmailDomainFormTouched = {};
      for (const key of Object.keys(values) as (keyof AllowedEmailDomainFormValues)[]) {
        allTouched[key] = true;
      }
      setTouchedState(allTouched);

      // Validate
      const validationErrors = validate(values);
      setErrors(validationErrors);

      if (Object.keys(validationErrors).length > 0) {
        return;
      }

      if (onSubmit) {
        setIsSubmitting(true);
        try {
          await onSubmit(values as AllowedEmailDomainFormValues);
        } finally {
          setIsSubmitting(false);
        }
      }
    },
    [values, validate, onSubmit]
  );

  const getFieldProps = useCallback(
    (field: keyof AllowedEmailDomainFormValues) => ({
      name: String(field),
      value: values[field] ?? '',
      onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const target = e.target;
        let newValue: unknown;

        if (target.type === 'checkbox') {
          newValue = (target as HTMLInputElement).checked;
        } else if (target.type === 'number') {
          newValue = target.value === '' ? undefined : Number(target.value);
        } else {
          newValue = target.value;
        }

        setValue(field, newValue as AllowedEmailDomainFormValues[typeof field]);
      },
      onBlur: () => setTouched(field),
    }),
    [values, setValue, setTouched]
  );

  // Build state object
  const state: AllowedEmailDomainFormState = {
    values,
    errors,
    touched,
    isSubmitting,
    isDirty,
    isValid,
    isSubmitted,
  };

  // Build actions object
  const actions: AllowedEmailDomainFormActions = {
    setValue,
    setValues,
    setTouched,
    setError,
    validate: validateForm,
    reset,
    handleSubmit,
    getFieldProps,
  };

  return {
    ...state,
    ...actions,
  };
}

export default useAllowedEmailDomainFormState;
