/**
 * React hooks for AllowedEmailDomain using urql.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { useQuery, useMutation } from 'urql';
import type { AllowedEmailDomain, AllowedEmailDomainCreate, AllowedEmailDomainUpdate, PaginationParams } from '../types/generated';

// Import generated GraphQL operations
import {
  GetAllowedEmailDomainQuery,
  ListAllowedEmailDomainsQuery,  CreateAllowedEmailDomainMutation,  UpdateAllowedEmailDomainMutation,  DeleteAllowedEmailDomainMutation,} from '../graphql';

/** Hook result for single AllowedEmailDomain query */
export interface UseAllowedEmailDomainResult {
  data: AllowedEmailDomain | null;
  loading: boolean;
  error: Error | null;
  refetch: () => void;
}

/** Hook result for AllowedEmailDomain list query */
export interface UseAllowedEmailDomainListResult {
  data: AllowedEmailDomain[];
  loading: boolean;
  error: Error | null;
  totalCount: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  refetch: () => void;
}

/** Hook result for mutations */
export interface UseAllowedEmailDomainMutationsResult {  create: (data: AllowedEmailDomainCreate) => Promise<AllowedEmailDomain | null>;  update: (id: number, data: AllowedEmailDomainUpdate) => Promise<AllowedEmailDomain | null>;  remove: (id: number) => Promise<boolean>;  loading: boolean;
  error: Error | null;
}

/**
 * Hook for fetching a single AllowedEmailDomain by ID.
 */
export function useAllowedEmailDomain(id: number | null): UseAllowedEmailDomainResult {
  const [result, reexecute] = useQuery({
    query: GetAllowedEmailDomainQuery,
    variables: { id: id! },
    pause: id === null,
  });

  return {
    data: result.data?.allowedEmailDomain ?? null,
    loading: result.fetching,
    error: result.error ?? null,
    refetch: reexecute,
  };
}

/**
 * Hook for fetching a list of AllowedEmailDomains with pagination.
 */
export function useAllowedEmailDomainList(
  pagination?: PaginationParams
): UseAllowedEmailDomainListResult {
  const [result, reexecute] = useQuery({
    query: ListAllowedEmailDomainsQuery,
    variables: {
      pagination: pagination ? {
        page: pagination.page ?? 1,
        pageSize: pagination.pageSize ?? 20,
      } : undefined,
    },
  });

  const connection = result.data?.allowedEmailDomains;

  return {
    data: connection?.edges.map((e: { node: AllowedEmailDomain }) => e.node) ?? [],
    loading: result.fetching,
    error: result.error ?? null,
    totalCount: connection?.totalCount ?? 0,
    hasNextPage: connection?.pageInfo.hasNextPage ?? false,
    hasPreviousPage: connection?.pageInfo.hasPreviousPage ?? false,
    refetch: reexecute,
  };
}

/**
 * Hook for AllowedEmailDomain mutations (create, update, delete).
 */
export function useAllowedEmailDomainMutations(): UseAllowedEmailDomainMutationsResult {  const [createResult, executeCreate] = useMutation(CreateAllowedEmailDomainMutation);  const [updateResult, executeUpdate] = useMutation(UpdateAllowedEmailDomainMutation);  const [deleteResult, executeDelete] = useMutation(DeleteAllowedEmailDomainMutation);
  const loading = createResult.fetching || updateResult.fetching || deleteResult.fetching;
  const error = createResult.error ?? updateResult.error ?? deleteResult.error ?? null;

  return {    create: async (data) => {
      const result = await executeCreate({ input: data });
      return result.data?.createAllowedEmailDomain ?? null;
    },    update: async (id, data) => {
      const result = await executeUpdate({ id, input: data });
      return result.data?.updateAllowedEmailDomain ?? null;
    },    remove: async (id) => {
      const result = await executeDelete({ id });
      return result.data?.deleteAllowedEmailDomain ?? false;
    },    loading,
    error,
  };
}

/**
 * Combined hook for all AllowedEmailDomain operations.
 */
export function useAllowedEmailDomains(pagination?: PaginationParams) {
  const list = useAllowedEmailDomainList(pagination);
  const mutations = useAllowedEmailDomainMutations();

  return {
    ...list,
    ...mutations,
  };
}
