/**
 * React hooks for Subdomain using urql.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { useQuery, useMutation } from 'urql';
import type { Subdomain, SubdomainCreate, SubdomainUpdate, PaginationParams } from '../types/generated';

// Import generated GraphQL operations
import {
  GetSubdomainQuery,
  ListSubdomainsQuery,  CreateSubdomainMutation,  UpdateSubdomainMutation,  DeleteSubdomainMutation,} from '../graphql';

/** Hook result for single Subdomain query */
export interface UseSubdomainResult {
  data: Subdomain | null;
  loading: boolean;
  error: Error | null;
  refetch: () => void;
}

/** Hook result for Subdomain list query */
export interface UseSubdomainListResult {
  data: Subdomain[];
  loading: boolean;
  error: Error | null;
  totalCount: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  refetch: () => void;
}

/** Hook result for mutations */
export interface UseSubdomainMutationsResult {  create: (data: SubdomainCreate) => Promise<Subdomain | null>;  update: (id: number, data: SubdomainUpdate) => Promise<Subdomain | null>;  remove: (id: number) => Promise<boolean>;  loading: boolean;
  error: Error | null;
}

/**
 * Hook for fetching a single Subdomain by ID.
 */
export function useSubdomain(id: number | null): UseSubdomainResult {
  const [result, reexecute] = useQuery({
    query: GetSubdomainQuery,
    variables: { id: id! },
    pause: id === null,
  });

  return {
    data: result.data?.subdomain ?? null,
    loading: result.fetching,
    error: result.error ?? null,
    refetch: reexecute,
  };
}

/**
 * Hook for fetching a list of Subdomains with pagination.
 */
export function useSubdomainList(
  pagination?: PaginationParams
): UseSubdomainListResult {
  const [result, reexecute] = useQuery({
    query: ListSubdomainsQuery,
    variables: {
      pagination: pagination ? {
        page: pagination.page ?? 1,
        pageSize: pagination.pageSize ?? 20,
      } : undefined,
    },
  });

  const connection = result.data?.subdomains;

  return {
    data: connection?.edges.map((e: { node: Subdomain }) => e.node) ?? [],
    loading: result.fetching,
    error: result.error ?? null,
    totalCount: connection?.totalCount ?? 0,
    hasNextPage: connection?.pageInfo.hasNextPage ?? false,
    hasPreviousPage: connection?.pageInfo.hasPreviousPage ?? false,
    refetch: reexecute,
  };
}

/**
 * Hook for Subdomain mutations (create, update, delete).
 */
export function useSubdomainMutations(): UseSubdomainMutationsResult {  const [createResult, executeCreate] = useMutation(CreateSubdomainMutation);  const [updateResult, executeUpdate] = useMutation(UpdateSubdomainMutation);  const [deleteResult, executeDelete] = useMutation(DeleteSubdomainMutation);
  const loading = createResult.fetching || updateResult.fetching || deleteResult.fetching;
  const error = createResult.error ?? updateResult.error ?? deleteResult.error ?? null;

  return {    create: async (data) => {
      const result = await executeCreate({ input: data });
      return result.data?.createSubdomain ?? null;
    },    update: async (id, data) => {
      const result = await executeUpdate({ id, input: data });
      return result.data?.updateSubdomain ?? null;
    },    remove: async (id) => {
      const result = await executeDelete({ id });
      return result.data?.deleteSubdomain ?? false;
    },    loading,
    error,
  };
}

/**
 * Combined hook for all Subdomain operations.
 */
export function useSubdomains(pagination?: PaginationParams) {
  const list = useSubdomainList(pagination);
  const mutations = useSubdomainMutations();

  return {
    ...list,
    ...mutations,
  };
}
