/**
 * React hooks for User using urql.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { useQuery, useMutation } from 'urql';
import type { User, UserCreate, UserUpdate, PaginationParams } from '../types/generated';

// Import generated GraphQL operations
import {
  GetUserQuery,
  ListUsersQuery,  CreateUserMutation,  UpdateUserMutation,  DeleteUserMutation,} from '../graphql';

/** Hook result for single User query */
export interface UseUserResult {
  data: User | null;
  loading: boolean;
  error: Error | null;
  refetch: () => void;
}

/** Hook result for User list query */
export interface UseUserListResult {
  data: User[];
  loading: boolean;
  error: Error | null;
  totalCount: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  refetch: () => void;
}

/** Hook result for mutations */
export interface UseUserMutationsResult {  create: (data: UserCreate) => Promise<User | null>;  update: (id: number, data: UserUpdate) => Promise<User | null>;  remove: (id: number) => Promise<boolean>;  loading: boolean;
  error: Error | null;
}

/**
 * Hook for fetching a single User by ID.
 */
export function useUser(id: number | null): UseUserResult {
  const [result, reexecute] = useQuery({
    query: GetUserQuery,
    variables: { id: id! },
    pause: id === null,
  });

  return {
    data: result.data?.user ?? null,
    loading: result.fetching,
    error: result.error ?? null,
    refetch: reexecute,
  };
}

/**
 * Hook for fetching a list of Users with pagination.
 */
export function useUserList(
  pagination?: PaginationParams
): UseUserListResult {
  const [result, reexecute] = useQuery({
    query: ListUsersQuery,
    variables: {
      pagination: pagination ? {
        page: pagination.page ?? 1,
        pageSize: pagination.pageSize ?? 20,
      } : undefined,
    },
  });

  const connection = result.data?.users;

  return {
    data: connection?.edges.map((e: { node: User }) => e.node) ?? [],
    loading: result.fetching,
    error: result.error ?? null,
    totalCount: connection?.totalCount ?? 0,
    hasNextPage: connection?.pageInfo.hasNextPage ?? false,
    hasPreviousPage: connection?.pageInfo.hasPreviousPage ?? false,
    refetch: reexecute,
  };
}

/**
 * Hook for User mutations (create, update, delete).
 */
export function useUserMutations(): UseUserMutationsResult {  const [createResult, executeCreate] = useMutation(CreateUserMutation);  const [updateResult, executeUpdate] = useMutation(UpdateUserMutation);  const [deleteResult, executeDelete] = useMutation(DeleteUserMutation);
  const loading = createResult.fetching || updateResult.fetching || deleteResult.fetching;
  const error = createResult.error ?? updateResult.error ?? deleteResult.error ?? null;

  return {    create: async (data) => {
      const result = await executeCreate({ input: data });
      return result.data?.createUser ?? null;
    },    update: async (id, data) => {
      const result = await executeUpdate({ id, input: data });
      return result.data?.updateUser ?? null;
    },    remove: async (id) => {
      const result = await executeDelete({ id });
      return result.data?.deleteUser ?? false;
    },    loading,
    error,
  };
}

/**
 * Combined hook for all User operations.
 */
export function useUsers(pagination?: PaginationParams) {
  const list = useUserList(pagination);
  const mutations = useUserMutations();

  return {
    ...list,
    ...mutations,
  };
}
