"""GraphQL filter input types for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from typing import Annotated

import strawberry

from .common import DateTimeFilter, IntFilter, StringFilter


@strawberry.input(description="Filter conditions for Subdomain fields")
class SubdomainWhereInput:
    """Where input for filtering Subdomain entities."""

    # ID filter
    id: IntFilter | None = None
    name: StringFilter | None = None
    ownerId: StringFilter | None = None
    ipAddress: StringFilter | None = None
    status: StringFilter | None = None
    dnsRecordId: StringFilter | None = None
    port: IntFilter | None = None
    releasedAt: DateTimeFilter | None = None
    cooldownUntil: DateTimeFilter | None = None


@strawberry.input(description="Filter Subdomain list relation")
class SubdomainListRelationFilter:
    """Filter for Subdomain list relations.

    - some: At least one related entity matches the filter
    - none: No related entities match the filter
    - every: All related entities match the filter
    """

    some: (
        Annotated[
            "SubdomainWhereInput",
            strawberry.lazy("prisme_api.api.graphql._generated.filters.subdomain"),
        ]
        | None
    ) = None
    none: (
        Annotated[
            "SubdomainWhereInput",
            strawberry.lazy("prisme_api.api.graphql._generated.filters.subdomain"),
        ]
        | None
    ) = None
    every: (
        Annotated[
            "SubdomainWhereInput",
            strawberry.lazy("prisme_api.api.graphql._generated.filters.subdomain"),
        ]
        | None
    ) = None


__all__ = [
    "SubdomainListRelationFilter",
    "SubdomainWhereInput",
]
