"""GraphQL filter input types for User.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from typing import Annotated

import strawberry

from .common import BoolFilter, DateTimeFilter, IntFilter, StringFilter


@strawberry.input(description="Filter conditions for User fields")
class UserWhereInput:
    """Where input for filtering User entities."""

    # ID filter
    id: IntFilter | None = None
    email: StringFilter | None = None
    passwordHash: StringFilter | None = None
    emailVerified: BoolFilter | None = None
    emailVerificationToken: StringFilter | None = None
    mfaEnabled: BoolFilter | None = None
    mfaSecret: StringFilter | None = None
    subdomainLimit: IntFilter | None = None
    isAdmin: BoolFilter | None = None
    passwordResetToken: StringFilter | None = None
    passwordResetTokenExpiresAt: DateTimeFilter | None = None
    emailVerificationTokenExpiresAt: DateTimeFilter | None = None
    failedLoginAttempts: IntFilter | None = None
    lockedUntil: DateTimeFilter | None = None
    githubId: StringFilter | None = None
    username: StringFilter | None = None
    roles: StringFilter | None = None
    isActive: BoolFilter | None = None
    apiKeys: (
        Annotated[
            "APIKeyListRelationFilter",
            strawberry.lazy("prisme_api.api.graphql._generated.filters.api_key"),
        ]
        | None
    ) = None
    subdomains: (
        Annotated[
            "SubdomainListRelationFilter",
            strawberry.lazy("prisme_api.api.graphql._generated.filters.subdomain"),
        ]
        | None
    ) = None


__all__ = [
    "UserWhereInput",
]
