/**
 * Auth API client — REST endpoints with cookie sessions.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || '';

async function apiPost<T>(path: string, body: unknown): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    credentials: 'include',
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const data = await response.json().catch(() => ({}));
    throw new Error(data.detail || `Request failed: ${response.status}`);
  }

  return response.json();
}

// ── Types ──────────────────────────────────────────────────────

export interface LoginResponse {
  requires_mfa: boolean;
  user?: Record<string, unknown> | null;
}

export interface MFASetupResponse {
  totp_uri: string;
  secret: string;
}

// ── Auth API ───────────────────────────────────────────────────

export async function signup(
  email: string,
  username: string,
  password: string
): Promise<{ message: string }> {
  return apiPost('/api/auth/signup', { email, username, password });
}

export async function login(
  email: string,
  password: string
): Promise<LoginResponse> {
  return apiPost('/api/auth/login', { email, password });
}

export async function loginMFA(
  email: string,
  code: string
): Promise<LoginResponse> {
  return apiPost('/api/auth/login/mfa', { email, code });
}

export async function verifyEmail(
  token: string
): Promise<{ message: string; user: Record<string, unknown> }> {
  return apiPost('/api/auth/verify-email', { token });
}

export async function resendVerification(
  email: string
): Promise<{ message: string }> {
  return apiPost('/api/auth/resend-verification', { email });
}

export async function forgotPassword(
  email: string
): Promise<{ message: string }> {
  return apiPost('/api/auth/forgot-password', { email });
}

export async function resetPassword(
  token: string,
  password: string
): Promise<{ message: string; user: Record<string, unknown> }> {
  return apiPost('/api/auth/reset-password', { token, password });
}

export async function setupMFA(): Promise<MFASetupResponse> {
  return apiPost('/api/auth/mfa/setup', {});
}

export async function verifyMFASetup(
  code: string
): Promise<{ message: string }> {
  return apiPost('/api/auth/mfa/verify-setup', { code });
}

export async function disableMFA(
  password: string
): Promise<{ message: string }> {
  return apiPost('/api/auth/mfa/disable', { password });
}

export function getGitHubLoginUrl(): string {
  return `${API_BASE_URL}/api/auth/github/login`;
}
