"""Authentik authentication module.

AUTO-GENERATED BY PRISM - DO NOT EDIT
Exports for OIDC authentication with Authentik.
"""

from prisme_api.auth.config import authentik_settings, get_authentik_settings
from prisme_api.auth.dependencies import (
    CurrentActiveUser,
    CurrentUser,
    get_current_active_user,
    get_current_user,
    require_roles,
)
from prisme_api.auth.oidc import OIDCClient, OIDCError, oidc_client

__all__ = [
    "CurrentActiveUser",
    "CurrentUser",
    "OIDCClient",
    "OIDCError",
    "authentik_settings",
    "get_authentik_settings",
    "get_current_active_user",
    "get_current_user",
    "oidc_client",
    "require_roles",
]
