"""Authentik authentication module.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
Exports for OIDC authentication with Authentik.
"""

from prisme_api.auth.api_key_service import (
    APIKeyError,
    APIKeyService,
    api_key_service,
)
from prisme_api.auth.config import authentik_settings, get_authentik_settings
from prisme_api.auth.dependencies import (
    CurrentActiveUser,
    CurrentUser,
    get_current_active_user,
    get_current_user,
    get_current_user_optional,
    require_roles,
)
from prisme_api.auth.oidc import OIDCClient, OIDCError, oidc_client

__all__ = [
    "APIKeyError",
    "APIKeyService",
    "CurrentActiveUser",
    "CurrentUser",
    "OIDCClient",
    "OIDCError",
    "api_key_service",
    "authentik_settings",
    "get_authentik_settings",
    "get_current_active_user",
    "get_current_user",
    "get_current_user_optional",
    "oidc_client",
    "require_roles",
]
