"""Authentik OIDC configuration.

AUTO-GENERATED BY PRISM - DO NOT EDIT
Configuration settings for Authentik OIDC integration.
"""

from __future__ import annotations

import os
from functools import lru_cache

from pydantic_settings import BaseSettings


class AuthentikSettings(BaseSettings):
    """Authentik OIDC settings loaded from environment variables."""

    # OIDC Configuration
    client_id: str = os.getenv("AUTHENTIK_CLIENT_ID", "")
    client_secret: str = os.getenv("AUTHENTIK_CLIENT_SECRET", "")
    issuer_url: str = os.getenv("AUTHENTIK_ISSUER_URL", "")

    # URLs (derived from issuer_url if not set)
    authorize_url: str = os.getenv("AUTHENTIK_AUTHORIZE_URL", "")
    token_url: str = os.getenv("AUTHENTIK_TOKEN_URL", "")
    userinfo_url: str = os.getenv("AUTHENTIK_USERINFO_URL", "")
    jwks_url: str = os.getenv("AUTHENTIK_JWKS_URL", "")
    logout_url: str = os.getenv("AUTHENTIK_LOGOUT_URL", "")

    # Application URLs
    redirect_uri: str = os.getenv("AUTHENTIK_REDIRECT_URI", "")
    post_logout_redirect_uri: str = os.getenv("AUTHENTIK_POST_LOGOUT_REDIRECT_URI", "")

    # Authentik base URL (for Flow Executor API)
    authentik_base_url: str = os.getenv("AUTHENTIK_BASE_URL", "")

    # JWT secret for self-issued session tokens
    jwt_secret: str = os.getenv("JWT_SECRET", "change-me-in-production")

    # Flow slugs
    login_flow_slug: str = os.getenv("AUTHENTIK_LOGIN_FLOW_SLUG", "madewithprisme-authentication")
    enrollment_flow_slug: str = os.getenv(
        "AUTHENTIK_ENROLLMENT_FLOW_SLUG", "madewithprisme-enrollment"
    )

    recovery_flow_slug: str = os.getenv("AUTHENTIK_RECOVERY_FLOW_SLUG", "madewithprisme-recovery")

    # GitHub OAuth (direct, bypassing Authentik UI)
    github_client_id: str = os.getenv("GITHUB_CLIENT_ID", "")
    github_client_secret: str = os.getenv("GITHUB_CLIENT_SECRET", "")
    github_redirect_uri: str = os.getenv("GITHUB_REDIRECT_URI", "")

    # Webhook Configuration
    webhook_secret: str = os.getenv("AUTHENTIK_WEBHOOK_SECRET", "")

    # Session Configuration
    session_cookie_name: str = "prisme_api_session"
    session_max_age: int = 60 * 60 * 24 * 7  # 7 days

    model_config = {"env_prefix": ""}

    def model_post_init(self, __context) -> None:
        """Derive URLs from issuer_url if not explicitly set."""
        if self.issuer_url:
            base = self.issuer_url.rstrip("/")
            if not self.authorize_url:
                self.authorize_url = f"{base}/authorize/"
            if not self.token_url:
                self.token_url = f"{base}/token/"
            if not self.userinfo_url:
                self.userinfo_url = f"{base}/userinfo/"
            if not self.jwks_url:
                # JWKS is typically at the root of the provider
                provider_base = "/".join(base.split("/")[:-2])
                self.jwks_url = f"{provider_base}/jwks/"
            if not self.logout_url:
                self.logout_url = f"{base}/end-session/"


@lru_cache
def get_authentik_settings() -> AuthentikSettings:
    """Get cached Authentik settings.

    Returns:
        Cached AuthentikSettings instance
    """
    return AuthentikSettings()


authentik_settings = get_authentik_settings()
