"""Authentication configuration.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
Settings for JWT sessions, email, OAuth, and security.
"""

from __future__ import annotations

from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class AuthSettings(BaseSettings):
    """Authentication settings loaded from environment variables."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # JWT secret for self-issued session tokens
    jwt_secret: str = "change-me-in-production"

    # Session Configuration
    session_cookie_name: str = "prisme_api_session"
    session_max_age: int = 604800

    # Email (Resend)
    resend_api_key: str = ""
    email_from: str = "MadeWithPris.me <noreply@madewithpris.me>"
    frontend_url: str = "http://localhost:5173"

    # Account lockout
    max_failed_login_attempts: int = 5
    lockout_duration_minutes: int = 15

    # Token expiry
    email_verification_token_hours: int = 24
    password_reset_token_hours: int = 1

    # GitHub OAuth
    github_client_id: str = ""
    github_client_secret: str = ""
    github_redirect_uri: str = ""


@lru_cache
def get_auth_settings() -> AuthSettings:
    """Get cached auth settings."""
    return AuthSettings()


auth_settings = get_auth_settings()
