"""Authentik authentication dependencies.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
FastAPI dependencies for OIDC-based authentication with Authentik.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import Cookie, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from prisme_api.auth.config import authentik_settings
from prisme_api.auth.oidc import OIDCError, oidc_client
from prisme_api.database import get_db
from prisme_api.models.user import User


async def get_session_token(
    session_token: str | None = Cookie(
        None,
        alias=authentik_settings.session_cookie_name,
    ),
) -> str:
    """Extract session token from cookie.

    Args:
        session_token: Session cookie value

    Returns:
        Session token string

    Raises:
        HTTPException: If no session token is present (401)
    """
    if not session_token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return session_token


async def get_current_user(
    session_token: Annotated[str, Depends(get_session_token)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> User:
    """Get current authenticated user from session.

    The session token contains the Authentik user ID (sub claim).
    We look up the corresponding local user record.

    Args:
        session_token: JWT session token from cookie
        db: Database session

    Returns:
        Authenticated user object

    Raises:
        HTTPException: If token is invalid or user not found (401)
    """
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )

    try:
        # Validate the session token (which is the ID token from Authentik)
        claims = await oidc_client.validate_id_token(session_token)
        authentik_id = claims.get("sub")

        if not authentik_id:
            raise credentials_exception

    except OIDCError:
        raise credentials_exception from None

    # Fetch user from database by Authentik ID
    result = await db.execute(select(User).where(User.authentik_id == authentik_id))
    user = result.scalar_one_or_none()

    if user is None:
        # User authenticated with Authentik but no local record exists
        # This can happen if webhooks are delayed - create user from token claims
        user = await _create_user_from_claims(claims, db)

    return user


async def _create_user_from_claims(
    claims: dict,
    db: AsyncSession,
) -> User:
    """Create a local user from OIDC token claims.

    Args:
        claims: Decoded ID token claims
        db: Database session

    Returns:
        Newly created user
    """
    authentik_id = claims.get("sub")
    email = claims.get("email", f"{claims.get('preferred_username', 'user')}@local")
    username = claims.get("preferred_username", claims.get("sub"))

    # Extract groups from claims (Authentik includes them in ID token)
    groups = claims.get("groups", [])
    roles = groups if groups else ["user"]

    user = User(
        authentik_id=authentik_id,
        email=email,
        username=username,
        is_active=True,
        roles=roles,
    )

    db.add(user)
    await db.commit()
    await db.refresh(user)

    return user


async def get_current_active_user(
    current_user: Annotated[User, Depends(get_current_user)],
) -> User:
    """Get current active user (checks is_active flag).

    Args:
        current_user: User from get_current_user dependency

    Returns:
        Active user object

    Raises:
        HTTPException: If user is inactive (403)
    """
    if not current_user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User account is inactive",
        )
    return current_user


async def get_current_user_optional(
    db: Annotated[AsyncSession, Depends(get_db)],
    session_token: str | None = Cookie(
        None,
        alias=authentik_settings.session_cookie_name,
    ),
) -> User | None:
    """Get current user if authenticated, or None if not.

    Args:
        db: Database session
        session_token: JWT session token from cookie (optional)

    Returns:
        User if authenticated, None otherwise
    """
    if not session_token:
        return None

    try:
        claims = await oidc_client.validate_id_token(session_token)
        authentik_id = claims.get("sub")

        if not authentik_id:
            return None

        result = await db.execute(select(User).where(User.authentik_id == authentik_id))
        return result.scalar_one_or_none()

    except OIDCError:
        return None


def require_roles(*required_roles: str):
    """Dependency factory for role-based access control.

    Usage:
        @router.get("/admin", dependencies=[Depends(require_roles("admin"))])

    Args:
        *required_roles: One or more role names required for access

    Returns:
        FastAPI dependency function that checks user roles
    """

    async def check_roles(
        current_user: Annotated[User, Depends(get_current_active_user)],
    ) -> User:
        """Check if user has required roles."""
        user_roles = set(current_user.roles or [])

        # Check for wildcard or matching role
        if "*" in required_roles or any(role in user_roles for role in required_roles):
            return current_user

        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Required roles: {', '.join(required_roles)}",
        )

    return check_roles


# Type aliases for convenience in route definitions
CurrentUser = Annotated[User, Depends(get_current_user)]
CurrentActiveUser = Annotated[User, Depends(get_current_active_user)]
