"""Pydantic schemas for AllowedEmailDomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

from datetime import datetime

from pydantic import ConfigDict, Field

from .base import SchemaBase


class AllowedEmailDomainBase(SchemaBase):
    """Whitelisted email domains for user signup"""

    domain: str = Field(max_length=255, description="Email domain (e.g., 'example.com')")
    is_active: bool = Field(description="Whether this domain is currently allowed")
    description: str | None = Field(
        default=None, max_length=500, description="Optional description/notes about this domain"
    )


class AllowedEmailDomainCreate(AllowedEmailDomainBase):
    """Schema for creating a AllowedEmailDomain."""

    is_active: bool | None = Field(
        default=True, description="Whether this domain is currently allowed"
    )


class AllowedEmailDomainUpdate(SchemaBase):
    """Schema for updating a AllowedEmailDomain. All fields are optional."""

    domain: str | None = Field(
        default=None, max_length=255, description="Email domain (e.g., 'example.com')"
    )
    is_active: bool | None = Field(
        default=True, description="Whether this domain is currently allowed"
    )
    description: str | None = Field(
        default=None, max_length=500, description="Optional description/notes about this domain"
    )


class AllowedEmailDomainRead(AllowedEmailDomainBase):
    """Schema for reading a AllowedEmailDomain."""

    id: int
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AllowedEmailDomainFilter(SchemaBase):
    """Filter schema for listing AllowedEmailDomains."""

    domain: str | None = None
    domain_like: str | None = None
    is_active: bool | None = None
    description: str | None = None
    created_after: datetime | None = None
    created_before: datetime | None = None
