"""Pydantic schemas for APIKey.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

from datetime import datetime

from pydantic import ConfigDict, Field

from .base import SchemaBase


class APIKeyBase(SchemaBase):
    """API keys for user authentication"""

    user_id: int = Field(description="The user who owns this API key")
    key_hash: str = Field(max_length=255, description="Hashed API key (SHA256)")
    key_prefix: str = Field(
        max_length=20, description="API key prefix for identification (e.g., prisme_live_sk_xxx)"
    )
    name: str = Field(max_length=100, description="Human-readable name for the API key")
    last_used_at: datetime | None = Field(
        default=None, description="Last time this API key was used"
    )
    expires_at: datetime | None = Field(
        default=None, description="When this API key expires (null = never)"
    )
    is_active: bool = Field(description="Whether this API key is active")


class APIKeyCreate(APIKeyBase):
    """Schema for creating a APIKey."""

    is_active: bool | None = Field(default=True, description="Whether this API key is active")


class APIKeyUpdate(SchemaBase):
    """Schema for updating a APIKey. All fields are optional."""

    user_id: int | None = Field(default=None, description="The user who owns this API key")
    key_hash: str | None = Field(
        default=None, max_length=255, description="Hashed API key (SHA256)"
    )
    key_prefix: str | None = Field(
        default=None,
        max_length=20,
        description="API key prefix for identification (e.g., prisme_live_sk_xxx)",
    )
    name: str | None = Field(
        default=None, max_length=100, description="Human-readable name for the API key"
    )
    last_used_at: datetime | None = Field(
        default=None, description="Last time this API key was used"
    )
    expires_at: datetime | None = Field(
        default=None, description="When this API key expires (null = never)"
    )
    is_active: bool | None = Field(default=True, description="Whether this API key is active")


class APIKeyRead(APIKeyBase):
    """Schema for reading a APIKey."""

    id: int
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class APIKeyFilter(SchemaBase):
    """Filter schema for listing APIKeys."""

    user_id: int | None = None
    key_hash: str | None = None
    key_prefix: str | None = None
    name: str | None = None
    last_used_at: datetime | None = None
    expires_at: datetime | None = None
    is_active: bool | None = None
    created_after: datetime | None = None
    created_before: datetime | None = None
