"""Pydantic schemas for Subdomain.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import ConfigDict, Field

from .base import SchemaBase


class SubdomainBase(SchemaBase):
    """A managed madewithpris.me subdomain"""

    name: str = Field(
        min_length=3,
        max_length=63,
        pattern=r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$",
        description="Subdomain name (e.g., 'myapp')",
    )
    owner_id: int | None = Field(default=None, description="The user who owns this subdomain")
    ip_address: str | None = Field(
        default=None,
        max_length=45,
        pattern=r"^(\d{1,3}\.){3}\d{1,3}$",
        description="IPv4 address for the A record",
    )
    status: Literal["reserved", "active", "suspended", "released"] = Field(
        description="Current status of the subdomain"
    )
    dns_record_id: str | None = Field(
        default=None, max_length=50, description="Hetzner DNS record ID"
    )


class SubdomainCreate(SubdomainBase):
    """Schema for creating a Subdomain."""

    status: Literal["reserved", "active", "suspended", "released"] | None = Field(
        default="reserved", description="Current status of the subdomain"
    )


class SubdomainUpdate(SchemaBase):
    """Schema for updating a Subdomain. All fields are optional."""

    name: str | None = Field(
        default=None,
        min_length=3,
        max_length=63,
        pattern=r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$",
        description="Subdomain name (e.g., 'myapp')",
    )
    owner_id: int | None = Field(default=None, description="The user who owns this subdomain")
    ip_address: str | None = Field(
        default=None,
        max_length=45,
        pattern=r"^(\d{1,3}\.){3}\d{1,3}$",
        description="IPv4 address for the A record",
    )
    status: Literal["reserved", "active", "suspended", "released"] | None = Field(
        default="reserved", description="Current status of the subdomain"
    )
    dns_record_id: str | None = Field(
        default=None, max_length=50, description="Hetzner DNS record ID"
    )


class SubdomainRead(SubdomainBase):
    """Schema for reading a Subdomain."""

    id: int
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SubdomainFilter(SchemaBase):
    """Filter schema for listing Subdomains."""

    name: str | None = None
    name_like: str | None = None
    owner_id: int | None = None
    ip_address: str | None = None
    status: str | None = None
    dns_record_id: str | None = None
    created_after: datetime | None = None
    created_before: datetime | None = None
