"""Pydantic schemas for User.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

from datetime import datetime

from pydantic import ConfigDict, Field

from .base import SchemaBase


class UserBase(SchemaBase):
    """User account for prisme.dev"""

    email: str = Field(max_length=255, description="User email address")
    password_hash: str | None = Field(
        default=None, max_length=255, description="Hashed password (bcrypt)"
    )
    email_verified: bool = Field(description="Whether email has been verified")
    email_verification_token: str | None = Field(
        default=None, max_length=255, description="Token for email verification"
    )
    mfa_enabled: bool = Field(description="Whether MFA is enabled")
    mfa_secret: str | None = Field(default=None, max_length=255, description="TOTP MFA secret")
    subdomain_limit: int = Field(description="Maximum number of subdomains allowed")
    is_admin: bool = Field(description="Whether user has admin privileges")


class UserCreate(UserBase):
    """Schema for creating a User."""

    email_verified: bool | None = Field(
        default=False, description="Whether email has been verified"
    )
    mfa_enabled: bool | None = Field(default=False, description="Whether MFA is enabled")
    subdomain_limit: int | None = Field(
        default=5, description="Maximum number of subdomains allowed"
    )
    is_admin: bool | None = Field(default=False, description="Whether user has admin privileges")


class UserUpdate(SchemaBase):
    """Schema for updating a User. All fields are optional."""

    email: str | None = Field(default=None, max_length=255, description="User email address")
    password_hash: str | None = Field(
        default=None, max_length=255, description="Hashed password (bcrypt)"
    )
    email_verified: bool | None = Field(
        default=False, description="Whether email has been verified"
    )
    email_verification_token: str | None = Field(
        default=None, max_length=255, description="Token for email verification"
    )
    mfa_enabled: bool | None = Field(default=False, description="Whether MFA is enabled")
    mfa_secret: str | None = Field(default=None, max_length=255, description="TOTP MFA secret")
    subdomain_limit: int | None = Field(
        default=5, description="Maximum number of subdomains allowed"
    )
    is_admin: bool | None = Field(default=False, description="Whether user has admin privileges")


class UserRead(UserBase):
    """Schema for reading a User."""

    id: int
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None

    model_config = ConfigDict(from_attributes=True)


class UserFilter(SchemaBase):
    """Filter schema for listing Users."""

    email: str | None = None
    email_like: str | None = None
    password_hash: str | None = None
    email_verified: bool | None = None
    email_verification_token: str | None = None
    mfa_enabled: bool | None = None
    mfa_secret: str | None = None
    subdomain_limit: int | None = None
    is_admin: bool | None = None

    # Relationship filters
    api_keys_id: int | None = None
    api_keys_ids: list[int] | None = None
    subdomains_id: int | None = None
    subdomains_ids: list[int] | None = None
    created_after: datetime | None = None
    created_before: datetime | None = None
    include_deleted: bool = False
