"""GraphQL schema.

⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
"""

from __future__ import annotations

import strawberry
from strawberry.fastapi import GraphQLRouter

from ._generated.context import get_context
from ._generated.mutations import APIKeyMutations, SubdomainMutations, UserMutations
from ._generated.queries import APIKeyQueries, SubdomainQueries, UserQueries


@strawberry.type(description="Prisme.dev API - GraphQL API")
class Query(UserQueries, APIKeyQueries, SubdomainQueries):
    """Managed subdomain service for prisme.dev"""

    pass


@strawberry.type(description="Prisme.dev API - GraphQL mutations")
class Mutation(UserMutations, APIKeyMutations, SubdomainMutations):
    """Prisme.dev API GraphQL mutations."""

    pass


schema = strawberry.Schema(
    query=Query,
    mutation=Mutation,
)


def get_graphql_router() -> GraphQLRouter:
    """Create the GraphQL router for FastAPI."""
    return GraphQLRouter(
        schema,
        context_getter=get_context,
    )


__all__ = ["Mutation", "Query", "get_graphql_router", "schema"]
