/**
 * Component tests for AllowedEmailDomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '../utils';
import { AllowedEmailDomainForm } from '../../components/allowed-email-domain/AllowedEmailDomainForm';
import { AllowedEmailDomainTable } from '../../components/allowed-email-domain/AllowedEmailDomainTable';
import { AllowedEmailDomainDetail } from '../../components/allowed-email-domain/AllowedEmailDomainDetail';
import type { AllowedEmailDomain } from '../../types/generated';

// Mock data
const mockAllowedEmailDomain: AllowedEmailDomain = {
  id: 1,
  domain: 'test string',
  isActive: true,
  description: 'test string',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

describe('AllowedEmailDomainForm', () => {
  it('renders form fields', () => {
    const onSubmit = vi.fn();

    render(<AllowedEmailDomainForm onSubmit={onSubmit} />);

    // Check that form renders by looking for the submit button
    expect(screen.getByRole('button', { name: /save/i })).toBeInTheDocument();
  });

  it('calls onSubmit with form data', async () => {
    const onSubmit = vi.fn();

    render(<AllowedEmailDomainForm onSubmit={onSubmit} />);

    // Fill in form fields and submit
    const submitButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(submitButton);

    await waitFor(() => {
      // onSubmit should be called (may fail validation)
    });
  });

  it('displays loading state', () => {
    const onSubmit = vi.fn();

    render(<AllowedEmailDomainForm onSubmit={onSubmit} loading={true} />);

    const submitButton = screen.getByRole('button', { name: /saving/i });
    expect(submitButton).toBeDisabled();
  });
});

describe('AllowedEmailDomainTable', () => {
  it('renders table with data', () => {
    const data = [mockAllowedEmailDomain];

    render(<AllowedEmailDomainTable data={data} />);

    expect(screen.getByRole('table')).toBeInTheDocument();
  });

  it('shows empty state when no data', () => {
    render(<AllowedEmailDomainTable data={[]} />);

    expect(screen.getByText(/no.*found/i)).toBeInTheDocument();
  });

  it('renders table rows with data', () => {
    const data = [mockAllowedEmailDomain];

    render(<AllowedEmailDomainTable data={data} />);

    // Check that table body has rows
    expect(screen.getAllByRole('row').length).toBeGreaterThan(1);
  });

  it('calls onEdit when edit button is clicked', () => {
    const data = [mockAllowedEmailDomain];
    const onEdit = vi.fn();

    render(<AllowedEmailDomainTable data={data} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalledWith(mockAllowedEmailDomain);
  });

  it('calls onDelete when delete button is clicked', () => {
    const data = [mockAllowedEmailDomain];
    const onDelete = vi.fn();

    render(<AllowedEmailDomainTable data={data} onDelete={onDelete} />);

    const deleteButton = screen.getByRole('button', { name: /delete/i });
    fireEvent.click(deleteButton);

    expect(onDelete).toHaveBeenCalledWith(mockAllowedEmailDomain);
  });
});

describe('AllowedEmailDomainDetail', () => {
  it('renders detail view', () => {
    render(<AllowedEmailDomainDetail data={mockAllowedEmailDomain} />);

    expect(screen.getByText(`AllowedEmailDomain #${mockAllowedEmailDomain.id}`)).toBeInTheDocument();
  });

  it('calls onEdit when edit button is clicked', () => {
    const onEdit = vi.fn();

    render(<AllowedEmailDomainDetail data={mockAllowedEmailDomain} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalled();
  });

  it('calls onBack when back button is clicked', () => {
    const onBack = vi.fn();

    render(<AllowedEmailDomainDetail data={mockAllowedEmailDomain} onBack={onBack} />);

    const backButton = screen.getByRole('button', { name: /back/i });
    fireEvent.click(backButton);

    expect(onBack).toHaveBeenCalled();
  });
});
