/**
 * Component tests for APIKey.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '../utils';
import { APIKeyForm } from '../../components/api-key/APIKeyForm';
import { APIKeyTable } from '../../components/api-key/APIKeyTable';
import { APIKeyDetail } from '../../components/api-key/APIKeyDetail';
import type { APIKey } from '../../types/generated';

// Mock data
const mockAPIKey: APIKey = {
  id: 1,
  userId: 1,
  keyHash: 'test string',
  keyPrefix: 'test string',
  name: 'test string',
  lastUsedAt: '2024-01-01T00:00:00Z',
  expiresAt: '2024-01-01T00:00:00Z',
  isActive: true,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

describe('APIKeyForm', () => {
  it('renders form fields', () => {
    const onSubmit = vi.fn();

    render(<APIKeyForm onSubmit={onSubmit} />);

    // Check that form renders by looking for the submit button
    expect(screen.getByRole('button', { name: /save/i })).toBeInTheDocument();
  });

  it('calls onSubmit with form data', async () => {
    const onSubmit = vi.fn();

    render(<APIKeyForm onSubmit={onSubmit} />);

    // Fill in form fields and submit
    const submitButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(submitButton);

    await waitFor(() => {
      // onSubmit should be called (may fail validation)
    });
  });

  it('displays loading state', () => {
    const onSubmit = vi.fn();

    render(<APIKeyForm onSubmit={onSubmit} loading={true} />);

    const submitButton = screen.getByRole('button', { name: /saving/i });
    expect(submitButton).toBeDisabled();
  });
});

describe('APIKeyTable', () => {
  it('renders table with data', () => {
    const data = [mockAPIKey];

    render(<APIKeyTable data={data} />);

    expect(screen.getByRole('table')).toBeInTheDocument();
  });

  it('shows empty state when no data', () => {
    render(<APIKeyTable data={[]} />);

    expect(screen.getByText(/no.*found/i)).toBeInTheDocument();
  });

  it('renders table rows with data', () => {
    const data = [mockAPIKey];

    render(<APIKeyTable data={data} />);

    // Check that table body has rows
    expect(screen.getAllByRole('row').length).toBeGreaterThan(1);
  });

  it('calls onEdit when edit button is clicked', () => {
    const data = [mockAPIKey];
    const onEdit = vi.fn();

    render(<APIKeyTable data={data} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalledWith(mockAPIKey);
  });

  it('calls onDelete when delete button is clicked', () => {
    const data = [mockAPIKey];
    const onDelete = vi.fn();

    render(<APIKeyTable data={data} onDelete={onDelete} />);

    const deleteButton = screen.getByRole('button', { name: /delete/i });
    fireEvent.click(deleteButton);

    expect(onDelete).toHaveBeenCalledWith(mockAPIKey);
  });
});

describe('APIKeyDetail', () => {
  it('renders detail view', () => {
    render(<APIKeyDetail data={mockAPIKey} />);

    expect(screen.getByText(`APIKey #${mockAPIKey.id}`)).toBeInTheDocument();
  });

  it('calls onEdit when edit button is clicked', () => {
    const onEdit = vi.fn();

    render(<APIKeyDetail data={mockAPIKey} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalled();
  });

  it('calls onBack when back button is clicked', () => {
    const onBack = vi.fn();

    render(<APIKeyDetail data={mockAPIKey} onBack={onBack} />);

    const backButton = screen.getByRole('button', { name: /back/i });
    fireEvent.click(backButton);

    expect(onBack).toHaveBeenCalled();
  });
});
