/**
 * Component tests for Subdomain.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '../utils';
import { SubdomainForm } from '../../components/subdomain/SubdomainForm';
import { SubdomainTable } from '../../components/subdomain/SubdomainTable';
import { SubdomainDetail } from '../../components/subdomain/SubdomainDetail';
import type { Subdomain } from '../../types/generated';

// Mock data
const mockSubdomain: Subdomain = {
  id: 1,
  name: 'test string',
  ownerId: 1,
  ipAddress: 'test string',
  status: 'reserved',
  dnsRecordId: 'test string',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

describe('SubdomainForm', () => {
  it('renders form fields', () => {
    const onSubmit = vi.fn();

    render(<SubdomainForm onSubmit={onSubmit} />);

    // Check that form renders by looking for the submit button
    expect(screen.getByRole('button', { name: /save/i })).toBeInTheDocument();
  });

  it('calls onSubmit with form data', async () => {
    const onSubmit = vi.fn();

    render(<SubdomainForm onSubmit={onSubmit} />);

    // Fill in form fields and submit
    const submitButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(submitButton);

    await waitFor(() => {
      // onSubmit should be called (may fail validation)
    });
  });

  it('displays loading state', () => {
    const onSubmit = vi.fn();

    render(<SubdomainForm onSubmit={onSubmit} loading={true} />);

    const submitButton = screen.getByRole('button', { name: /saving/i });
    expect(submitButton).toBeDisabled();
  });
});

describe('SubdomainTable', () => {
  it('renders table with data', () => {
    const data = [mockSubdomain];

    render(<SubdomainTable data={data} />);

    expect(screen.getByRole('table')).toBeInTheDocument();
  });

  it('shows empty state when no data', () => {
    render(<SubdomainTable data={[]} />);

    expect(screen.getByText(/no.*found/i)).toBeInTheDocument();
  });

  it('renders table rows with data', () => {
    const data = [mockSubdomain];

    render(<SubdomainTable data={data} />);

    // Check that table body has rows
    expect(screen.getAllByRole('row').length).toBeGreaterThan(1);
  });

  it('calls onEdit when edit button is clicked', () => {
    const data = [mockSubdomain];
    const onEdit = vi.fn();

    render(<SubdomainTable data={data} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalledWith(mockSubdomain);
  });

  it('calls onDelete when delete button is clicked', () => {
    const data = [mockSubdomain];
    const onDelete = vi.fn();

    render(<SubdomainTable data={data} onDelete={onDelete} />);

    const deleteButton = screen.getByRole('button', { name: /delete/i });
    fireEvent.click(deleteButton);

    expect(onDelete).toHaveBeenCalledWith(mockSubdomain);
  });
});

describe('SubdomainDetail', () => {
  it('renders detail view', () => {
    render(<SubdomainDetail data={mockSubdomain} />);

    expect(screen.getByText(`Subdomain #${mockSubdomain.id}`)).toBeInTheDocument();
  });

  it('calls onEdit when edit button is clicked', () => {
    const onEdit = vi.fn();

    render(<SubdomainDetail data={mockSubdomain} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalled();
  });

  it('calls onBack when back button is clicked', () => {
    const onBack = vi.fn();

    render(<SubdomainDetail data={mockSubdomain} onBack={onBack} />);

    const backButton = screen.getByRole('button', { name: /back/i });
    fireEvent.click(backButton);

    expect(onBack).toHaveBeenCalled();
  });
});
