/**
 * Component tests for User.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '../utils';
import { UserForm } from '../../components/user/UserForm';
import { UserTable } from '../../components/user/UserTable';
import { UserDetail } from '../../components/user/UserDetail';
import type { User } from '../../types/generated';

// Mock data
const mockUser: User = {
  id: 1,
  email: 'test string',
  passwordHash: 'test string',
  emailVerified: true,
  emailVerificationToken: 'test string',
  mfaEnabled: true,
  mfaSecret: 'test string',
  subdomainLimit: 42,
  isAdmin: true,
  authentikId: 'test string',
  username: 'test string',
  roles: { test: 'value' },
  isActive: true,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

describe('UserForm', () => {
  it('renders form fields', () => {
    const onSubmit = vi.fn();

    render(<UserForm onSubmit={onSubmit} />);

    // Check that form renders by looking for the submit button
    expect(screen.getByRole('button', { name: /save/i })).toBeInTheDocument();
  });

  it('calls onSubmit with form data', async () => {
    const onSubmit = vi.fn();

    render(<UserForm onSubmit={onSubmit} />);

    // Fill in form fields and submit
    const submitButton = screen.getByRole('button', { name: /save/i });
    fireEvent.click(submitButton);

    await waitFor(() => {
      // onSubmit should be called (may fail validation)
    });
  });

  it('displays loading state', () => {
    const onSubmit = vi.fn();

    render(<UserForm onSubmit={onSubmit} loading={true} />);

    const submitButton = screen.getByRole('button', { name: /saving/i });
    expect(submitButton).toBeDisabled();
  });
});

describe('UserTable', () => {
  it('renders table with data', () => {
    const data = [mockUser];

    render(<UserTable data={data} />);

    expect(screen.getByRole('table')).toBeInTheDocument();
  });

  it('shows empty state when no data', () => {
    render(<UserTable data={[]} />);

    expect(screen.getByText(/no.*found/i)).toBeInTheDocument();
  });

  it('renders table rows with data', () => {
    const data = [mockUser];

    render(<UserTable data={data} />);

    // Check that table body has rows
    expect(screen.getAllByRole('row').length).toBeGreaterThan(1);
  });

  it('calls onEdit when edit button is clicked', () => {
    const data = [mockUser];
    const onEdit = vi.fn();

    render(<UserTable data={data} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalledWith(mockUser);
  });

  it('calls onDelete when delete button is clicked', () => {
    const data = [mockUser];
    const onDelete = vi.fn();

    render(<UserTable data={data} onDelete={onDelete} />);

    const deleteButton = screen.getByRole('button', { name: /delete/i });
    fireEvent.click(deleteButton);

    expect(onDelete).toHaveBeenCalledWith(mockUser);
  });
});

describe('UserDetail', () => {
  it('renders detail view', () => {
    render(<UserDetail data={mockUser} />);

    expect(screen.getByText(`User #${mockUser.id}`)).toBeInTheDocument();
  });

  it('calls onEdit when edit button is clicked', () => {
    const onEdit = vi.fn();

    render(<UserDetail data={mockUser} onEdit={onEdit} />);

    const editButton = screen.getByRole('button', { name: /edit/i });
    fireEvent.click(editButton);

    expect(onEdit).toHaveBeenCalled();
  });

  it('calls onBack when back button is clicked', () => {
    const onBack = vi.fn();

    render(<UserDetail data={mockUser} onBack={onBack} />);

    const backButton = screen.getByRole('button', { name: /back/i });
    fireEvent.click(backButton);

    expect(onBack).toHaveBeenCalled();
  });
});
