/**
 * GraphQL operations index.
 *
 * ⚠️ AUTO-GENERATED BY PRISM - DO NOT EDIT
 */

export { client } from './client';
export { graphql, gql } from './gql';

// User
export * from './fragments/user';
export * from './queries/user';
export * from './mutations/user';

// APIKey
export * from './fragments/api_key';
export * from './queries/api_key';
export * from './mutations/api_key';

// Subdomain
export * from './fragments/subdomain';
export * from './queries/subdomain';
export * from './mutations/subdomain';

// AllowedEmailDomain
export * from './fragments/allowed_email_domain';
export * from './queries/allowed_email_domain';
export * from './mutations/allowed_email_domain';
